### ISSUE TITLE
demo locks on the 2nd mainloop() call in demo part

### ISSUE THREAD

**Issue by herve-guerin-pro** [ragardner/tksheet#1]
@ragardner 
Hi,
_(I wanted to send you a message before posting my issue, but I didn't find how) : Yours module look really great !
I begin to use it and found a little thing which looks like a bug in the demo part ..._

My issue : 
Demo locks on the 2nd mainloop() call in demo part of the _tksheet.py file.
I suppose that it is because one of the mainloop() calls should be removed,
and I suggest to remove the 2nd one.
_As I am quite new on github, I would like to create a pull request for that in the next few days if you agree with that, so I propose to fix this quite simple issue by myself._

Best regards,
Herve

**Comment by ragardner** [comment]
Hi @herve-guerin-pro 

Thanks for your interest in the library and for noticing the error, I am quite new to github also

I have removed one of the mainloops in the demo and it should work correctly now, I have also updated the library on PyPi so installing it via pip should have a working demo now also

I'm sorry but as it was a bug I decided to fix it as soon as possible myself, but if you have any further suggestions for the library you could create a pull request for those, or if you wanted to have your own version of the library on github you could clone the repository
