### ISSUE TITLE
Show cell value when mouse hovering ?

### ISSUE THREAD

**Issue by longk15t** [ragardner/tksheet#10]
Hello @ragardner 

Thanks for your effort on creating this amazing library.
Can we show the cell's value in a tooltip or sth like that when we hover on it ?
I read the DOCUMENTATION.md and didn't found any method to support this (I'm sorry if I missed)

Thanks and best regards,
longk15t

**Comment by ragardner** [comment]
Hi there,

Unfortunately there is no such code currently within the library, but I have written this code to show you possibly how it might be done:

This line goes after you've created your sheet widget:
`self.sheet_demo.bind("<Motion>", self.mouse_motion)`

and then the motion function would look something like this I guess:
```python
def mouse_motion(self, event):
        region = self.sheet_demo.identify_region(event)
        if region == "table":
            row = self.sheet_demo.identify_row(event, allow_end = False)
            column = self.sheet_demo.identify_column(event, allow_end = False)
            if row is not None and column is not None:
                #code for tooltip popup goes here
                pass
```

**Comment by longk15t** [comment]
Thanks for your reply, best wishes for you.
