### ISSUE TITLE
Drop down for whole column

### ISSUE THREAD

**Issue by Geert86** [ragardner/tksheet#100]
Hi there,
first up, great work.

Is there a way to asign a dropdown to a whole column at once?
Have tried r=all, c="any number" but that only seems active for deleting dorpdown boxes.

Thanks in advance.

**Comment by Geert86** [comment]
I have manipulated the code in _tksheet.py to this:
it works for me. 
perhaps you can use this for a next release:

`    def create_dropdown(self,
                        r = 0,
                        c = 0,
                        values = [],
                        set_value = None,
                        state = "readonly",
                        redraw = False,
                        selection_function = None,
                        modified_function = None):
        if r == "all":
            r_=0
            total_rows = self.MT.total_data_rows()
            while r_ <= total_rows:
                self.MT.create_dropdown(r=r_,
                                        c=c,
                                        values=values,
                                        set_value=set_value,
                                        state=state,
                                        redraw=redraw,
                                        selection_function=selection_function,
                                        modified_function=modified_function)
                r_ = r_+1
        else:
            self.MT.create_dropdown(r = r,
                                c = c,
                                values = values,
                                set_value = set_value,
                                state = state,
                                redraw = redraw,
                                selection_function = selection_function,
                                modified_function = modified_function)`

**Comment by ragardner** [comment]
Thanks very much for your suggestion, I forgot to mention this was added to a previous version, I am not sure which version it was added to but `5.3.3` is the latest
