### ISSUE TITLE
self.highlight_cells() affects self.extra_bindings("cell_select", func = self.edit_cell)

### ISSUE THREAD

**Issue by TheOtherMarcus** [ragardner/tksheet#102]
I have enabled cell editing with

self.extra_bindings("cell_select", func = self.edit_cell)

and edit_cell(() calls

self.create_text_editor(...)

I also highlight the same cell with

self.highlight_cells(row=row, column=1, bg=self.pingBg(typ), redraw=False)

This worked fine in an earlier version I used during the fall 2021. When I updated tksheet to be able to use checkbox() things changed. A click on an highlighted cell usually only marks it and does not open the editor. Only sometimes the editor opens. Non highlighted cells works perfectly.

**Comment by ragardner** [comment]
Sorry about this, there's some recently introduced issues regarding behavior of custom implementations of text editors I think, I will try to sort it out but no promises
