### ISSUE TITLE
fix proposal : add USER_OS detection to avoid side effect on Linux platform

### ISSUE THREAD

**Issue by skedus** [ragardner/tksheet#105]
Hi Ragardner,
I found a side effect on Linux platform the `<Option-Return>` is interpreted as a `<Return>` binding

https://github.com/ragardner/tksheet/blob/def2f77ad7d72b6da86e9dc66d3163e4dfff6e7f/tksheet/_tksheet_main_table.py#L4894

by adding a simple USER_OS check, all is working well on Windows and Linux Platform (I do not test it on Mac)

```
        if USER_OS == 'Darwin':
            self.text_editor.textedit.bind(
                "<Option-Return>", lambda x: self.text_editor_newline_binding(r, c)
            )
```
Is it possible to add this in your next release ?
Thank you

**Comment by ragardner** [comment]
Sorry for delay and thanks for report,

I made this edit in `5.2.9`
