### ISSUE TITLE
[Question] How do I invoke "Delete"

### ISSUE THREAD

**Issue by KirklandBordeaux** [ragardner/tksheet#108]
This might be a really dumb question. How is delete supposed to work in the sheet? I have added "delete" to the function call sheet.enable_bindings() but hitting the "delete" key while a cell is selected does nothing. 

As a check I added an extra binding with the function call

`sheet.extra_bindings("begin_delete", func = my_delete_action)`

and hitting the "delete" key while a cell is selected does not cause this function to be called. I feel like I am just missing something obvious. If it's helpful I can produce an example that demonstrates this, but I feel it is likely that it's just me missing something rather than a bug.

**Comment by ragardner** [comment]
Hm, I am not sure what is wrong, it seems to work on my end

if it's not too much trouble I would greatly appreciate an example

**Comment by KirklandBordeaux** [comment]
@ragardner, 

Thank you for looking at it. Here is a very simple example that fails to delete on my machine. (I had to change the file extension to txt for this message window to accept it.) The commands cut, copy, and paste all work fine. Delete does nothing: no actions, no error in python.

If it's useful, I included the list of python packages I am using in "environment.txt".

I am running on a Macintosh. Is it possible that that is the issue, somehow?

Thanks,

KB

[tksheet_delete_problem.py.txt](https://github.com/ragardner/tksheet/files/8111878/tksheet_delete_problem.py.txt)
[environment.txt](https://github.com/ragardner/tksheet/files/8111903/environment.txt)

**Comment by ragardner** [comment]
Thanks a lot for the example and environment info,

Unfortunately the delete key works normally for me, there doesn't seem to be any libraries/packages which would cause such an issue for you

It must be the operating system or the keyboard or keyboard layout or something along those lines, unless the delete key you're using is the numpad one? I am unsure if that would make a difference or not but I couldn't seem to bind the numpad delete key in tkinter and I don't even have a numpad available to test it

I also don't have mac os to test it on there : / I am unsure how to proceed

**Comment by KirklandBordeaux** [comment]
Thank you, and apologies for the delay. 

To be clear, I am using the delete key on the main keyboard, not a keypad. I also think the issue is MacOS platform-related. I can try to investigate on my system, if you have any suggestions for how I might do that. 

One thought I had: is there any facility within tksheet to capture and/or print all keystrokes? Or can you propose some code that I might add to my script to do that? If the delete key is somehow encoded differently than you expect, that would explain it.

Thanks,

KB

**Comment by ragardner** [comment]
Regarding the capturing of keystrokes in tkinter, I think you can add inside `_tksheet.py` `self.bind_all('<Key>', <your_function_goes_here>)` underneath the `__init__` function

If `bind_all` won't work then use `.bind` inside the other files such as `_tksheet_main_table.py` and the row index, top left and headers files

`<Key>` is not to be changed, it's literally key I think which should bind all keystrokes but not mouse clicks as shown in this answer https://stackoverflow.com/questions/55603282/keybind-that-binds-to-every-key-in-tkinter

I am not sure how to get all mouse clicks as well though

It's a great idea actually, you should be able to print out the event object and see which button is being pressed

**Comment by KirklandBordeaux** [comment]
@ragardner, Thank you. That was very helpful. I was able to trap and print keystrokes, and sure enough, the Delete button on my MacBook is actually a backspace:

`<KeyPress event keysym=BackSpace keycode=855638143 x=60 y=57>`

I can use this to add a binding for BackSpace in my program, but it would be great if you could enable deleting to work properly in tksheet by default on MacOS.

**Comment by ragardner** [comment]
Thanks for the quick report, I would definitely like to resolve this soon, a couple of questions though sorry

 - Does fn-delete or cmd-delete do anything?

 - Also just to clarify, in theory hitting BackSpace while cells are selected and `"edit_cell"` is enabled would cause a cell editor window to be opened but nothing at all happens for you?

**Comment by KirklandBordeaux** [comment]
@ragardner,

In answer to your questions:

- fn-delete deletes the cell. Using the method of trapping keystrokes, it produces the following:

```
<KeyPress event state=Mod4 keysym=Super_L keycode=1057028350 x=35 y=182>
<KeyPress event state=Mod4 keysym=Delete keycode=1962997544 x=35 y=182>

```

So it is apparently correctly interpreted as Delete. 

- cmd-delete does nothing. 

- Hitting Delete while cells are selected and `"edit_cell"` is enabled does nothing.

**Comment by ragardner** [comment]
@KirklandBordeaux Thanks very much for testing that,

I can make the Delete key work like Delete on windows but then you'd be without a Backspace binding or alternatively I can fix the Backspace binding and leave Delete on fn-delete

I don't mind doing either, which do you think would be best?

**Comment by KirklandBordeaux** [comment]
@ragardner 

My simple answer is that it would be better for me for my Delete key to work like Delete on Windows. 

But I don't want you to do something that you think other MacOS users might not like or find reasonable. I can work around it, now that I know how to.

Thanks,

KB

**Comment by KirklandBordeaux** [comment]
@ragardner I can verify that hitting the delete key on MacOS (which invokes BackSpace) now opens up a cell editor window and deletes the contents.

Thank you for your efforts. I think this closes the issue from my perspective.
