### ISSUE TITLE
Resize sheet when user resize window

### ISSUE THREAD

**Issue by longk15t** [ragardner/tksheet#11]
Hello @ragardner, have a good day.

I have a question, can we resize the sheet widget when I resize the main window so I can see horizontal + vertical scrollbar of the sheet ?

Currently, this is what I get when I downsize the main window
<img width="708" alt="Screenshot 2020-03-04 at 1 16 39 PM" src="https://user-images.githubusercontent.com/6722910/75850668-6bdc9400-5e1a-11ea-8da4-be9e29701dac.png">

Thanks and best regards,
longk15t

**Comment by ragardner** [comment]
I think there are a few possible solutions, I'll start with the easiest

If you have put the `Sheet()` inside a frame using `.grid()` then you can try the code:
```python
self.my_frame_name.grid_columnconfigure(<integer column that the Sheet() was put in>, weight = 1)
self.my_frame_name.grid_rowconfigure(<integer row that the Sheet() was put in>, weight = 1)
```
Or if you used `.pack()` then you can try messing about with `fill` and `expand` as shown in this question:
https://stackoverflow.com/questions/28089942/difference-between-fill-and-expand-options-for-tkinter-pack-method

If these don't work or are not applicable let me know

**Comment by longk15t** [comment]
@ragardner your are savior, that worked !

**Comment by aquib-sh** [comment]
tried it but no luck

![image](https://user-images.githubusercontent.com/44388122/130072511-ef8a1bef-c352-486d-9760-04374399b02b.png)


I used 


```
        self.sheet_frame.grid(row=1, column=1, sticky=W)
        self.sheet_frame.grid_columnconfigure(1, weight=1)
        self.sheet_frame.grid_rowconfigure(1, weight=1)

```
