### ISSUE TITLE
delete_row

### ISSUE THREAD

**Issue by iurisegtovich** [ragardner/tksheet#112]
Hi, i found that in the test file, everytime a row is selected it gets deleted because of the following block of code.

```
    def all_extra_bindings(self, event):
        print (event)
        if event and event[0] == "select_row":
            self.sheet.delete_row(event[1])
```
I understand this is a general purpose feature, but i found it confusing being in the test file and I would change as follows

```
    def all_extra_bindings(self, event):
        print (event)
        if event and event[0] == "select_row":
            #self.sheet.delete_row(event[1])
            print('you performed `select_row` event, you can run custom action from `all_extra_bindings` inside `if event and event[0] == "select_row":`')
```

**Comment by ragardner** [comment]
Yea sorry it's probably confusing, I have been messing around with it to test various updates and occassionally forget to delete the extra code

I will probably delete the folder and put more user friendly code into the documentation instead for people to copy
