### ISSUE TITLE
User input value not overriden by redraw

### ISSUE THREAD

**Issue by j-cote100** [ragardner/tksheet#121]
It's a bit difficult to explain, but I'll do my best.  I haven't seen anything related in the issues so far. 

I have a binding on 'end_edit_cell'.  Let's say I change cell(r=0, c=3) value to "90".  in the same function, I set the cell value to "BIO"
It seems that the user input is not overriden by redraw.  Same thing happen when reseting the whole sheet data. 
I tried redraw, refresh, update and it doesn't fix it.

note: I can change any other cell with  set_cell_data.  Only the current cell seems to be affected by this

I put a piece of code and some screenshots below so that you can try to replicate the issue. 

is it meant to be like this or maybe I'm missing a function that I should use instead to override the user input?

```
import tkinter as tk
from tksheet import Sheet


class Window(tk.Frame):
    def __init__(self, parent):
        self.parent = parent
        tk.Frame.__init__(self, self.parent)
        data = [[1, 2, 3, 4], [1, 2, 3, 4], [4, 5, 6, 7], [7, 6, 5, 4]]
        self.sheet = Sheet(self, data=data)
        self.sheet.set_all_column_widths()

        self.sheet.enable_bindings('all')

        self.sheet.extra_bindings('end_edit_cell', func=self.end_edit_cell)

        self.grid(sticky="nswe", rowspan=25)
        self.sheet.grid(row=0, column=0, rowspan=25, sticky="nswe")

    # BELOW WITH set_cell_data
    def end_edit_cell(self, event):
        r, c, mode, value, *_ = event
        # value stores the ser input in the cell

        # Try to override the user input to "BIO" -- doesn't work
        self.sheet.set_cell_data(r=r, c=c, value='BIO', redraw=True)

        # try to set a different cell than the active one to BIO(3,3) and it works
        self.sheet.set_cell_data(r=3, c=3, value='BIO(3,3)', redraw=True)
        self.sheet.set_all_column_widths()

    # # --- SAME BELOW but trying to set_sheet_data instead of cell ----
    # def end_edit_cell(self, event):
    #     r, c, mode, value, *_ = event
    #
    #     data = [['A', 'B', 'D', 'F'], [1, 2, 3, 4], [4, 5, 6, 7], ['ZZ', 'BB', 'VV', 'GG']]
    #     self.sheet.set_sheet_data(data=data, redraw=True)
    #
    #     self.sheet.set_all_column_widths()


if __name__ == '__main__':
    root = tk.Tk()
    Window(root)

    root.mainloop()
```

Initial table
![image](https://user-images.githubusercontent.com/72038677/164553079-40fc3f02-a0b8-4d98-a87f-40d638fdf398.png)

Changing cell(0,3) value for "90" then press Return, even with this line of code `self.sheet.set_cell_data(r=r, c=c, value='BIO', redraw=True)` ,the value in the cell stays "90"
However, as expected from the other line of code, cell(3,3) is set to "BIO(3,3)" `self.sheet.set_cell_data(r=3, c=3, value='BIO(3,3)', redraw=True)`
![image](https://user-images.githubusercontent.com/72038677/164553128-5816d6c0-6f4f-4fb7-bea5-1d4e436a4b15.png)![image](https://user-images.githubusercontent.com/72038677/164553175-8a8eba5d-f959-4fb9-885a-55f8ed5c960f.png)

Finally, to top it of, if I change the value in a cell, but instead of pressing Return, I click on the header, it works:
![image](https://user-images.githubusercontent.com/72038677/164554020-6f53b498-f252-42f4-8fcb-f1fd06ddc57c.png)![image](https://user-images.githubusercontent.com/72038677/164554066-777c0949-cbb2-4784-9f2c-620b51830a69.png)

Thanks for checking it out, I hope my explanation isn't too confusing

I tried on on both Python 3.7 and 3.10

**Comment by ragardner** [comment]
Thanks very much for the detailed report!

There's a couple of things going on here...

1st there was a bug where clicking on the header to focus out of the cell editor in the main table was simply closing the editor and not setting the cell

2nd there's something about the extra bindings for `end_edit_cell` which I didn't explain at all in the documentation, I have updated tksheet to `5.3.8` which includes the bug fix and this information in the docs:

 - For most of the `"end_..."` events the bound function is run before the value is set.
 - The bound function for `"end_edit_cell"` is run before the cell data is set in order that a return value can set the cell instead of the user input. Using the event you can assess the user input and if needed override it with a return value which is not `None`. if `None` is the return value then the user input will not be overridden.

Sorry about the confusion, I hope this helps though

**Comment by j-cote100** [comment]
Thank you! That small explanation makes total sense! 

As specified, adding a return value to the `end_edit_cell` event overrides the user input perfectly.

Many thanks and great work on this package it is a charm to use.
