### ISSUE TITLE
Freeze Pane

### ISSUE THREAD

**Issue by TheinHtayAung91** [ragardner/tksheet#123]
How can I do freeze pane row and column in tksheet?

**Comment by ragardner** [comment]
You can set the index to be a single column and the header to be a certain row, I have updated the documentation a bit to show how https://github.com/ragardner/tksheet/wiki#5-header-and-index

I know this isn't really freezing the rows/columns though

```
Using an integer int for argument newheaders makes the sheet use that row as a header e.g. headers(0) means the first row will be used as a header (the first row will not be hidden in the sheet though), this is sort of equivalent to freezing the row.
```

```
Using an integer int for argument newindex makes the sheet use that column as an index e.g. row_index(0) means the first column will be used as an index (the first column will not be hidden in the sheet though), this is sort of equivalent to freezing the column.
```

**Comment by TheinHtayAung91** [comment]
Thank you for reply.

I try as below.

self.sheet.row_index(newindex=3)

It can only freeze first column. I'd like to freeze start from column 3.

**Comment by ragardner** [comment]
Unfortunately you can only do one single column sorry

**Comment by TheinHtayAung91** [comment]
Noted with thanks.

It would be great if you could add that function.

Best Regards,
