### ISSUE TITLE
BUG: Function 'checkbox' throws error if parameter 'state' is NONE

### ISSUE THREAD

**Issue by ClaytonCurtis1947** [ragardner/tksheet#126]
In function 'checkbox':

The test for 'state' being 'normal' or 'disabled' throws an error if 'state' is NONE, which is the =default= for that parameter

Please consider changing
  if state.lower() in ("normal", "disabled"):

to
  if (state) and (state.lower() in ("normal", "disabled")):

**Comment by ragardner** [comment]
Thanks very much for pointing this out!

It should be fixed in `5.4.1` along with the 2nd such occurrence of the same code in the header version of the function.

**Comment by ClaytonCurtis1947** [comment]
Thanks for the reply and apologies for taking so long to respond!

I really like tksheet, which has made it much easier to code a couple of projects!

 

Three (sorry) questions:

1.	How can I tell which version I have installed, and what do I need to do to update it? (Just pip install it again?)
2.	What is your recommendation for a site or sites to communicate with the tksheet community? I’d like to find a place to ask questions and – hopefully – contribute.
3.	Your GitHub page for tksheet says “”Except for bug fixing I am no longer working on this repository”. Should I be following you elsewhere?

 

Thanks again.

Clayton Curtis

Newton, MA

**Comment by ragardner** [comment]
Hi Clayton, I'm sorry for such a late response,

1. Lately I have been updating the changelog with this information and you can use `pip install tksheet --upgrade` to update
2. There isn't such a community as far as I'm aware, either here or on stackoverflow is best I suppose, you're welcome to open an issue even if just for discussion
3. The place to follow me at the moment is here on github, I will update my page with links if that changes

Kind regards,

ragardner

**Comment by ClaytonCurtis1947** [comment]
Thanks!


-----Original Message-----
