### ISSUE TITLE
How do you color cells like in the readme?

### ISSUE THREAD

**Issue by ElonXXIII** [ragardner/tksheet#127]
I can't find the function to color cells as shown in the dark theme example screenshot in the readme.

**Comment by ragardner** [comment]
I am sorry that it was not clear enough, I have updated the docs to better explain how, see links below:

https://github.com/ragardner/tksheet/wiki#10-table-colors
https://github.com/ragardner/tksheet/wiki#11-highlighting-cells

And the code in this example:

https://github.com/ragardner/tksheet/wiki#29-example-readme-screenshot-code
