### ISSUE TITLE
Potential bug on the "total_rows" function

### ISSUE THREAD

**Issue by r-jaoui** [ragardner/tksheet#129]
In the function "total_rows", I get this error :

```
text = "\n".join(["j^|" for lines in range(n)]) if n > 1 else "j^|",
TypeError: '>' not supported between instances of 'tuple' and 'int'
```

I believe the error is on line **912** of the __tksheet.py_ module. Checking the syntax in the definition of the **default_rh** field (on module __tksheet_main_table.py_ line **2830**) I found this fix (that seems to work) :

Replace line **912** of the __tksheet.py_ module with the following :

`height = self.MT.GetLinesHeight(int(self.MT.default_rh[0]))`

instead of :

`height = self.MT.GetLinesHeight(self.MT.default_rh)`

Thanks !

**Comment by ragardner** [comment]
Thanks very much for pointing this out, it should be fixed now
