### ISSUE TITLE
Save TkSheet table as CSV-file ?

### ISSUE THREAD

**Issue by Prospekteur** [ragardner/tksheet#131]
I need a solution tosave my TkSheet tabel as csv. How to do that? Has someone a solution for that?

**Comment by EissaMD** [comment]
Here is my first comment in github, hope it help to solve your issue :)

```py
import csv

def sheet_to_csv(sheet):
    headers = sheet.headers()
    data = sheet.get_sheet_data()
    with open("output.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(data)
```

and then call the function eg:

```py

mysheet = Sheet(   ...   )
.
.
.
sheet_to_csv(mysheet )

```

**Comment by Prospekteur** [comment]
Wow;-) Thank you very much for your help! And keep on the great work;-)
Regards Benny Rieger 


    Am Sonntag, 9. Oktober 2022 um 23:25:36 MESZ hat EissaMD ***@***.***> Folgendes geschrieben:  
 
 


Here is my first comment in github, hope it help to solve your issue :)
import csv

def sheet_to_csv(sheet):
    headers = sheet.headers()
    data = sheet.get_sheet_data()
    with open("output.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(data)
and then call the function eg:
mysheet = Sheet(   ...   )
..
.
..
sheet_to_csv(mysheet )

**Comment by Prospekteur** [comment]
Hi,
I have one last question;-)
Your code solution to save the table worked great. Adjusted your code for my needs and now its works like a dream! THANK YOU,-). When Im clicking right mousebutton I can choose "Save Table" now and can save the table in my needed csv format after choosing the file destination. 
At the moment Im searching for a solution to add some mathematical functions to the mouse selected cells. For example multiplicate every selected cell with 2 to double every selected cell value. For now I only have access to the cell index but not to the values itself. Do you have a hint or solution for me how to add a multiplicate function for each selected cell?
Sorry for robbing your time, I will try further, but definitely need a bit help to get this cell multiplication function to work;-). Perhaps you can add something like that in the future in TKSheet code ;-)
Regards 
Benny
    Am Donnerstag, 13. Oktober 2022 um 23:17:07 MESZ hat Benny Rieger ***@***.***> Folgendes geschrieben:  
 
  Wow;-) Thank you very much for your help! And keep on the great work;-)
Regards Benny Rieger 


    Am Sonntag, 9. Oktober 2022 um 23:25:36 MESZ hat EissaMD ***@***.***> Folgendes geschrieben:  
 
 


Here is my first comment in github, hope it help to solve your issue :)
import csv

def sheet_to_csv(sheet):
    headers = sheet.headers()
    data = sheet.get_sheet_data()
    with open("output.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(data)
and then call the function eg:
mysheet = Sheet(   ...   )
..
.
..
sheet_to_csv(mysheet )

**Comment by Prospekteur** [comment]
After adjusting your code a bit Im able to save the table via right click menu after determining the storage folder;-) Works great. Thank you a lot!

**Comment by thmsmullee** [comment]
> After adjusting your code a bit Im able to save the table after determining the storage folder, via right click menu;-) Works great. Thank you a lot!

Can I have the code ? ;-)

**Comment by ragardner** [comment]
Sorry for the late reply,

I have added some basic csv file creation code to the documentation / wiki 

https://github.com/ragardner/tksheet/wiki#30-example-saving-tksheet-as-a-csv-file
