### ISSUE TITLE
[Question] Headers when hiding columns

### ISSUE THREAD

**Issue by hazeez** [ragardner/tksheet#132]
Hi, 
Thank you for the wonderful package
I have written code to hide the columns based on one of the threads. 
I have the following columns - A, B, C, D and E
If I hide column B, the header value changes to A, B, C and D whereas i want it to be A, C, D and E. 
Can you tell me a way of how to achieve this?
I have read the documentation and code to the best of my ability but i cannot make this out. 
Note: I am using default headers (letters) and not headers from my data.

**Comment by ragardner** [comment]
I'm sorry for taking so very long to respond,

Thanks for raising this issue, it should be fixed in version 5.5.0, please read the release notes if you plan on updating though, there have been some changes to argument and function names which may impact you
