### ISSUE TITLE
How to get mouse selected cell values and manipulate them with mathematical functions ?

### ISSUE THREAD

**Issue by Prospekteur** [ragardner/tksheet#133]
At the moment Im searching for a solution to add some mathematical functions to the mouse selected cells. For example multiplicate every selected cell with 2 to double every selected cell value. For now I only have access to the cell index but not to the values itself. Do anyone have a hint or solution for me how to add a multiplicate function for each selected cell (also if multiple cells are selected)?
So if multiple cells are selected with the mouse, I could multiplicate each selected cell by 2 (for doubling each value). Im able to get the selected cell index of each cell but, couldnt find a solution to be able to multiplicate each cell that is selected by 2 for example. I want to add the possibility to manipulate the selected cells by mathematical functions at the end;-)
Regards 
Benny

**Comment by CalJaDav** [comment]
This can be closed @ragardner. Answered [here](https://github.com/ragardner/tksheet/issues/148).
