### ISSUE TITLE
Changing font of specific cells/columns/rows with prepopulated data?

### ISSUE THREAD

**Issue by mikeyv19** [ragardner/tksheet#134]
Hi, this may be a basic question, as I am only a bigger.

I can't figure out how to change specific cell fonts, styles, and formats. I have a table where different styles are needed throughout (some rows bolded, some cells underlined, some font in a different color, some in italics.

The sheet loads with this data already populated. How can I select specific cells/columns/and rows and have the data load with the format I need for those cells?

`tsheet.font(("Arial", 12, "bold"))`

The above applies to my full sheet. Basically, how can I target that to certain cells? Like all of Row 3, and B5, and C3, and all of row 1?

I'll need various fonts and formats.

**Comment by ragardner** [comment]
Unfortunately this is impossible I'm sorry and I'm sorry for taking so very long to respond
