### ISSUE TITLE
Calls to update() impacting peformance

### ISSUE THREAD

**Issue by daniilS** [ragardner/tksheet#140]
`Sheet`, `MainTable` and `ColumnHeaders` all contain calls to `update()`. This forces the sheet to redraw multiple times, most noticeable when creating a `TopLevel` window with a sheet, which will change size on each redraw while the table is loading.

I can't immediately see a reason why `update()` was used where it is, but I might be missing something. If it is necessary to force a redraw while a Python function is still running, would it be worth using `update_idletasks()` instead? [It should have slightly less impact on performance.](https://wiki.tcl-lang.org/page/Update+considered+harmful)

**Comment by ragardner** [comment]
I have removed all the calls to `update()` in `tksheet` as per your suggestion in version 5.5.0,

Thank and sorry for the late reply
