### ISSUE TITLE
Default sheet input clips text input box

### ISSUE THREAD

**Issue by cpellet** [ragardner/tksheet#15]
Using default row height values and autoresize, text input is clipped in cells (see below)
![image](https://user-images.githubusercontent.com/18552249/78554290-2f31fd00-780b-11ea-834b-a1b33d85781f.png)

**Comment by ragardner** [comment]
Does making the following change in `_tksheet_main_table.py` fix the issue?

```python
def text_editor_newline_binding(self, event = None):
        #if self.GetLinesHeight(self.text_editor.get_num_lines() + 1) > self.text_editor.winfo_height():
        self.text_editor.config(height = self.text_editor.winfo_height() + self.xtra_lines_increment)
```

**Comment by cpellet** [comment]
I unfortunately do not have any development environment other than macOS to test this on right now but this does not fix the issue, even with the default starting template suggested in readme.md, so the issue, as well as the black border, seems to be specific to the platform. I will run some tests to try to fix this.

**Comment by ragardner** [comment]
@cpellet with version `4.5.9` I have attempted to remove the text editor border by changing `bd` and `highlightthickness` arguments, there should still be the blue frame border, which is separate

**Comment by cpellet** [comment]
`4.5.9` fixes the issue
