### ISSUE TITLE
Index dropdown not changing index vaue

### ISSUE THREAD

**Issue by CalJaDav** [ragardner/tksheet#151]
Row index dropdowns are not working correctly. On selecting a value we get the error:

File "C:\Users\CallumDavidson\OneDrive - Consilium\Documents\tksheet\tksheet\_tksheet_row_index.py", line 1477, in _set_cell_data
    self.MT._set_cell_data(r = r, c = self.MT._row_index, drow = drow, value = value, undo = True)
TypeError: _set_cell_data() got an unexpected keyword argument 'drow'

Looks like the MT._set_cell_data has no implementation for displayed row.

**Comment by ragardner** [comment]
FYI There's some more changes coming in the next version regarding the mess with dcol and drow in dropdowns and _set_cell_data

**Comment by ragardner** [comment]
In version `5.6.0` I have hopefully fixed a lot of these issues, let me know what you think

**Comment by CalJaDav** [comment]
Good patch! Nice little performance improvement also.
