### ISSUE TITLE
TableDropdown correction

### ISSUE THREAD

**Issue by skedus** [ragardner/tksheet#16]
Hi,
First, Thank you for this widget I was looking for.
I made some tests with cell editor such combobox with the following example I added in the demo:
**self.sheet.create_dropdown(3, 3, values=["AAA","BBB","CCC","DDD"], set_value="CCC", destroy_on_select=False )**
The initialization does not work because set_value is not part of combox config, with the following small correction it seems to work

Correction:
line 169 _tksheet_other_classes.py
Remove set_value from the init, set_value is done just below.
```
        ttk.Combobox.__init__(self,
                              parent,
                              font = font,
                              state = state,
                              values = values,
                              **#set_value = set_value,**
                              textvariable = self.displayed)
```
If it can help, that could be nice to have as well checkbox as cell editor
Thanks again

**Comment by ragardner** [comment]
Hello,

Sorry about that, it should be fixed in version 4.6.4 and the function has a few new arguments and the box should hug the cell size by using a frame internally, the new function looks like this:

```python
create_dropdown(r = 0,
                c = 0,
                values = [],
                set_value = None,
                state = "readonly",
                see = True,
                destroy_on_select = True,
                current = False,
                openbox = True,
                set_cell_on_select = True,
                redraw = True,
                recreate_selection_boxes = True)
```

`openbox` is for whether or not you want the box to be opened upon creation, redraw and recreate are for if `destroy_on_select` is `True`

**Comment by skedus** [comment]
Thanks for your quick answer, I made a new tests still at the end of the demo:

```
self.sheet.create_dropdown(3, 3, values=["AAA","BBB","CCC","DDD"],  set_value="CCC", see=False, openbox=False, destroy_on_select=False)
self.sheet.create_dropdown(4, 3, values=["AAA","BBB","CCC","DDD"],  set_value="BBB", see=False, openbox=False, destroy_on_select=False)
self.sheet.create_dropdown(5, 3, values=["AAA","BBB","CCC","DDD"],  set_value="DDD", see=False, openbox=False, destroy_on_select=False)
print (self.sheet.get_cell_data(3, 3))
print (self.sheet.get_cell_data(4, 3))
print (self.sheet.get_cell_data(5, 3))
```

Correction: I need to remove line 3867 in _tksheet_main_table (create_dropdown)

`self.destroy_dropdown()`

else all previous combox are not display only the last one (but may be this correction is too strong) sorry I do not yet read all code.

I saw as well that cell values are not really set with the print you can see old value are displayed (should be initial combo setup CCC BBB DDD in the example)

For my need a single checkbutton is enough and probably more simple to create ;-)

**Comment by ragardner** [comment]
Ah yeah, I see what you mean, unfortunately it's always been designed as a singular input thing and it will take a few days to overhaul the code to create and manage multiple dropdown boxes that persist as I have very little free time at the moment

**Comment by skedus** [comment]
I understand, no problem,
Thank you for your time

**Comment by ragardner** [comment]
@skedus Hello,

With version 4.6.6 I have added the basic functionality to create multiple persistent boxes which will update the underlying table upon creation and selection, I have removed the argument `openbox` as it was causing weird lag and focus issues, so you can try your code as below again:

```python
self.sheet.create_dropdown(3, 3, values=["AAA","BBB","CCC","DDD"],  set_value="CCC", see=False, destroy_on_select=False)
self.sheet.create_dropdown(4, 3, values=["AAA","BBB","CCC","DDD"],  set_value="BBB", see=False, destroy_on_select=False)
self.sheet.create_dropdown(5, 3, values=["AAA","BBB","CCC","DDD"],  set_value="DDD", see=False, destroy_on_select=False)
print (self.sheet.get_cell_data(3, 3))
print (self.sheet.get_cell_data(4, 3))
print (self.sheet.get_cell_data(5, 3))
```

Please note that actions such as cell resizing, undo, drag and drop etc will not really work while you have these persistent boxes up, I will slowly add more code to maintain their positions and size etc over the next couple of weeks

Let me know if there's a problem with the changes

**Comment by skedus** [comment]
Thank you for this update, It is working. But you are right many other things to do, to keep all functionalities (sorry for that)

I still do not know if it is the good approach, may by each cell should have a link to a specific class such, let say, Editor and various sub class EntryEditor (default one), ComboEditor ... which could be call only when edit cell and set the value ??  so non persistent as you did.
Then it could be possible to affect an Editor to cell, row, or column (even a custom one CustomEditor(Editor)) I do not know just thinking.

Anyway thanks again for your high level of response.
