### ISSUE TITLE
text vertical alignment

### ISSUE THREAD

**Issue by Medainus** [ragardner/tksheet#164]
Hi, I want to align text vertically. I couldn't find option for that. 
Can tksheet do align vertical?

![tksheet](https://user-images.githubusercontent.com/130649694/231708598-d1473533-1d5d-4070-a4df-e7645bce32f3.png)

**Comment by CalJaDav** [comment]
Hi @Medainus,
Unfortunately this is currently not a feature in tksheet, it is probably on a long list of features to include in a future patch. If you want, I would encourage you to have a go implementing it yourself and becoming a contributor. There are not a lot a lot of us working on it at the moment, actually it is pretty much a one-man show with @ragardner having written 99% of everything. 
Thanks for your patience!
C

**Comment by Medainus** [comment]
OK, Thanks to your reply @CalJaDav .
I'll try to modify or use different way.

**Comment by CalJaDav** [comment]
If you want to have a go, text is drawn onto the table in `MT.main_table_redraw_grid_and_text()`. For each cell, it gets the position of the top left corner of each cell and draws the text onto the canvas line by line. You'll want to add some logic to center the text in the cell and add an additional vertical alignment option in the `cell_options.`
