### ISSUE TITLE
Header dropdown covering column name

### ISSUE THREAD

**Issue by Joecadbert** [ragardner/tksheet#166]
When using create_header_dropdown's for filtering, The drop down box covers up the column name.
Cab both the header name and the dropdown  be shown at the same time?   Can a filter row be added?

**Comment by ragardner** [comment]
Regarding the header name, do you mean the letters indicating the index, e.g. A B C D E etc.

Regarding row filtering, this is currently the only example I have of doing that - 
https://github.com/ragardner/tksheet/wiki#28-example-header-dropdown-boxes-and-filtering

**Comment by Joecadbert** [comment]
Hello,  Thank you for the reply.
The top image in the attached picture is in debug mode and paused as the program is creating the header dropdowns.    The first three columns have the dropdown created and is covering the column name.  the second three columns are still showing the column names.  Once all of the column header dropdowns are created, the user may have a challenge determining what column is the one they want to filter.  This specific table has more than a 100 columns.

The desired appearance shown in the bottom image would be to have the column name above the column header dropdown.  Similar to the filter row effect in Excel.
Is this possible with settings?


![column_header_example](https://user-images.githubusercontent.com/126290823/233408498-c55b3aca-2915-4d8a-84fc-b60abf451b57.PNG)

**Comment by ragardner** [comment]
Ah I see, you'd like to display something in a header regardless of the value selected in it's dropdown box?

If this is the case then it's not currently possible, but let me know if that's what you'd like and I can get back to you about putting it in a future release (probably soon if the code is easy enough...)

**Comment by ragardner** [comment]
I have updated tksheet to `6.0.0` which includes a change to `create_header_dropdown` with a new keyword argument `text` which can display your header name over the cells actual value

see here for more info
https://github.com/ragardner/tksheet/wiki#create-a-dropdown-box-only-creates-the-arrow-and-border-and-sets-it-up-for-usage-does-not-pop-open-the-box

I have not done anything more for row filtering though sorry that will not likely be anytime soon if at all

**Comment by ragardner** [comment]
@Joecadbert Sorry for yet another message but just to let you know I have now added the capability to both show a header name over a dropdown value AND filter rows

Example here https://github.com/ragardner/tksheet/wiki#example-header-dropdown-boxes-and-row-filtering

**Comment by Joecadbert** [comment]
Thanks for the update.  I will take a look at the improvements.
Joe
