### ISSUE TITLE
Bug: Cannot resize row index

### ISSUE THREAD

**Issue by CalJaDav** [ragardner/tksheet#174]
Resizing row index does not appear to work. This is due to a call to `RI..auto_set_index_width()` in  `main_table_redraw_grid_and_text()` when `redraw_header` is set to `True`. Suggest moving this call to somewhere else, possibly to `__init__` because auto resizing only really needs to be called on initialisation and after edits to row index.

**Comment by ragardner** [comment]
Auto resize was intended to keep the index the right size for the numbers or letters that show when the row index variable is an empty list

You can disable auto resize with `auto_resize_default_row_index = False` though

Is this the right behavior in your opinion?

**Comment by CalJaDav** [comment]
No worries, my bad. Might write this up in docs at some point,
