### ISSUE TITLE
Problem with sheet.header_font

### ISSUE THREAD

**Issue by Subachao** [ragardner/tksheet#179]
Hello, i get trouble with the code "self.sheet.header_font(newfont = ("Arial", 14, "normal"))" and get TypeError: 'tuple' object is not callable, then I find out that your code get some problem in _tksheet_main_table.py
![image](https://github.com/ragardner/tksheet/assets/55833491/59737d7a-b6ba-4da9-a6a1-9019c5feb60a)
![image](https://github.com/ragardner/tksheet/assets/55833491/de45c862-a21c-4cf4-93e9-c3ae053f7a70)
After i change to "self.header_font" to "self.table_header_font" like you do with "self.table_font = newfont", it work!, so you can fix this code and maybe the other place
Thanks!

**Comment by ragardner** [comment]
Woops, sorry about that and thanks for pointing it out, must have been as a result of recently moving some variables around, will let you know here when it's fixed in a new release

**Comment by ragardner** [comment]
Thanks again and it should be fixed now in `6.1.4` https://github.com/ragardner/tksheet/blob/master/CHANGELOG.md
