### ISSUE TITLE
Question - last row in sheet

### ISSUE THREAD

**Issue by Alrmalli** [ragardner/tksheet#18]
Hello,
Thanks for your hard work,
I'd like to know how to get the last row in sheet / or the total number of available rows in sheet
without looping through the whole sheet,

**Comment by ragardner** [comment]
For the last row, as the sheet stores data as a list of lists
`print (self.sheet.get_sheet_data()[-1])`

For the total number of data rows
print (len(self.sheet.get_sheet_data()))

And just in case for some unlikely reason there is a difference between the two, for the total number of displayed rows
`print (len(self.sheet.get_row_heights()))`

You will find these functions demonstrated in the readme file or the front page of this repository
