### ISSUE TITLE
display_columns() not working as per wiki

### ISSUE THREAD

**Issue by Goldthing** [ragardner/tksheet#181]
Hi, while following the documentation in trying to hide columns I've found a slight issue.

From the Wiki entry on [hiding columns](https://github.com/ragardner/tksheet/wiki/Version-6#hiding-columns):

> Use argument `True` with `all_columns_displayed` to display all columns, however, there's no need to use `False` when `columns` is not `None`

However on following this advice while passing in a list to columns I was getting no errors, but also no columns were being hidden. Just after this there's the example

> Example usage to display specific columns only: `sheet.display_columns([2, 4, 7], all_displayed = False)`

adding in the `all_displayed = False` argument and all behaves as expected. Not sure if this is better classified as a bug or a documentation issue.

Thanks.

**Comment by ragardner** [comment]
Thanks for the report, you're correct sorry, the example usage is the right way, I updated the wiki and will do the docs file in the next update

**Comment by Goldthing** [comment]
Wow that was fast! Thank you
