### ISSUE TITLE
How to scroll two sheets at the same time

### ISSUE THREAD

**Issue by HenriqueEira** [ragardner/tksheet#191]
How to make both sheets scrooll at the same time when the mouse is over one of the sheets?

`tableFrame = customtkinter.CTkFrame(root, width=0.99*root.winfo_width(), height=0.85*root.winfo_height())
tableFrame.place(anchor="nw", relx=0.01, rely=0.01)
tableFrame.update()

sheet_r = Sheet(tableFrame, 
            show_top_left = False,
            set_all_heights_and_widths = False,show_row_index= False,
            #max_rh=1,
            width=int(tableFrame.winfo_width()/1.4), 
            height=int(tableFrame.winfo_height()),
            theme=helper.APPEARANCE_SHEET)

sheet_r.enable_bindings()
sheet_r.disable_bindings("delete", "edit_cell", "cut", "paste", "rc_insert_row", "rc_delete_row",
                       "rc_delete_column","edit_header", "rc_insert_column")
sheet_r.bind("<Double-Button-1>", doubleClick, add = None)

sheet_l = Sheet(tableFrame,show_x_scrollbar=False,
            show_y_scrollbar=False,
            show_top_left = False,
            set_all_heights_and_widths = False, 
            #max_rh=1,
            width=int(tableFrame.winfo_width()/3.63), 
            height=int(tableFrame.winfo_height()),
            theme=helper.APPEARANCE_SHEET)

sheet_l.enable_bindings()`

**Comment by ragardner** [comment]
Hello,

There's no immediately easy way to do this at the moment but I will try to add this functionality and release a new version with it in the coming days

**Comment by ragardner** [comment]
@HenriqueEira I have now added the scroll syncing functionality in version `6.2.2`. Documentation here:

https://github.com/ragardner/tksheet/wiki/Version-6#sync-scroll-positions-between-widgets

Please note however that it is not perfect when there are large differences between sheet sizes, it may be possible to improve this or perhaps it is fine the way it is

Let me know how what you think
