### ISSUE TITLE
How to change appereance of the Thsheet when bindings are disabled

### ISSUE THREAD

**Issue by janez111** [ragardner/tksheet#192]
Dear all,

i am new to the Python so please be patient with me. I am buliding tkinter GUI with tksheet tables. I want to change the appereance of table when  disabled. I assume that tksheet do not have options like tkinter etc., where You can configure ie button background with added argument like disabledbackground = 'grey'

so i tried like this:
if sheet.disable_bindings == True:
                         sheet = ts.Sheet(root,
                          theme = 'dark',
                          frame_bg = 'white',
                          table_fg = 'black',
                          table_bg = 'grey', 
                          table_grid_fg = 'black',
                          header_bg = '#073642')
I simply wanted to configure sheet with different color scheme when disabled Of course, it did not work. So is there a way to change appereance of the tksheet when bindings are disabled?

**Comment by ragardner** [comment]
Hello,

I am sorry to say that at the moment there is no setting inside tksheet to automatically handle this, the colors would have to be changed wherever your code disables (or enables) tksheets bindings

For example after your enable bindings line of code you would put:

```python
sheet.set_options(
frame_bg = ..., # your color for enabled here
table_fg = ..., # your color for enabled here
table_bg = ..., # your color for enabled here
table_grid_fg = ..., # your color for enabled here
header_bg = ..., # your color for enabled here
)
```

and after your disable bindings line of code you would put:

```python
sheet.set_options(
frame_bg = ..., # your color for disabled here
table_fg = ..., # your color for disabled here
table_bg = ..., # your color for disabled here
table_grid_fg = ..., # your color for disabled here
header_bg = ..., # your color for disabled here
)
```

These are all the color options you can use with `set_options()`

```python
header_bg
header_border_fg
header_grid_fg
header_fg
header_selected_cells_bg
header_selected_cells_fg
header_hidden_columns_expander_bg
index_bg
index_border_fg
index_grid_fg
index_fg
index_selected_cells_bg
index_selected_cells_fg
index_hidden_rows_expander_bg
top_left_bg
top_left_fg
frame_bg
table_bg
table_grid_fg
table_fg
table_selected_cells_border_fg
table_selected_cells_bg
table_selected_cells_fg
resizing_line_fg
drag_and_drop_bg
outline_thickness
outline_color
header_selected_columns_bg
header_selected_columns_fg
index_selected_rows_bg
index_selected_rows_fg
table_selected_rows_border_fg
table_selected_rows_bg
table_selected_rows_fg
table_selected_columns_border_fg
table_selected_columns_bg
table_selected_columns_fg
popup_menu_font
popup_menu_fg
popup_menu_bg
popup_menu_highlight_bg
popup_menu_highlight_fg
```

It seems in your above code your bindings are disabled to begin with, so if you're not immediately enabling your `Sheet` bindings you would pretty much do as you have:

```python
"""
going by your code here, assuming you have imported tksheet as ts
"""
sheet = ts.Sheet(root,
theme = 'dark',
frame_bg = 'white',
table_fg = 'black',
table_bg = 'grey',
table_grid_fg = 'black',
header_bg = '#073642')
```

Or you could use `set_options()` and put the disabled colors below the `Sheet()`s creation

Let me know if this doesn't help

**Comment by janez111** [comment]
Dear sir,

thanks for the help, your suggestion works prefect. I am also sorry for the late reply and appreciate Your time You spend for developing the tools for community.

Again, thank You very much.

Best regads, Janez

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
