### ISSUE TITLE
Mouse bindings and Mac

### ISSUE THREAD

**Issue by ragardner** [ragardner/tksheet#2]
The right click bindings might not work properly for Mac OS

**Comment by nama1arpit** [comment]
Currently, the following workaround works for me (because I don't use middle click for anything).

```
if sys.platform == "darwin":
    sheet.bind("<Button-3>", lambda e: sheet.event_generate("<Button-2>", x=e.x, y=e.y))
```

I believe the issue might be static mapping of mouse click binding within tksheet instead of dynamic binding based on the platform.

**Comment by nama1arpit** [comment]
Hi @ragardner,

Appreciate your prompt response and fix. However, it doesn't seem to work for my situation. Happy to provide any further relevant information.

**Comment by nama1arpit** [comment]
All good, that works for now. Thank you @ragardner.
