### ISSUE TITLE
Add prompt for wrong keyward args in get_sheet_data/get_cell_data/get_row_data/get_column_data

### ISSUE THREAD

**Issue by githubuser11123** [ragardner/tksheet#200]
For now, there is no hint when using wrong kwargs in method 'get_sheet_data', eg, 'get_dispalyed' instead of 'get_displayed'.
I think it would be wonderful to have prompt to avoid such spelling mistakes. 
Thanks.

**Comment by ragardner** [comment]
I have added these warnings in version `6.2.6`, thank you for the suggestion!
