### ISSUE TITLE
on Rpi5, OS debian bookworm, tksheet's sheet defined col-w & row-h of 10x16 cells size has slow/lagging mouse's cursor movement 

### ISSUE THREAD

**Issue by SamO6453** [ragardner/tksheet#207]
Hi Ragardner, 
we have been using tksheet ver 6.3.4 on rpi4B debian Bullseye, python3.9.2 in our application and the movements of the cursor in the table with small defined cell's area as small as wxh (17x8.5) are working great.  However, after we tested/run it on new OS rpi5 debian bookworm and python3.11.2, we have noticed the cursor is moving lagging/slowly.  Has anyone else seen this issue? I would like to have the source code tkhseet to debug this issue.  Thanks!

**Comment by ragardner** [comment]
Hello,

Thanks for your report,

I suspect the relevant sections of code are the functions:

```python
def mouse_motion(self, event):
    ...
```

Which are contained in the files:
- _tksheet_main_table.py
- _tksheet_row_index.py
- _tksheet_column_headers.py

Why they are causing lag under one environment but not another I am not sure

You could try commenting out the code in the functions or commenting out the line that binds those functions:

```python
("<Motion>", self, self.mouse_motion),
```

which is contained within `_tksheet_main_table.py`

To see what happens...

But I think what I will do longer term is make it so that mouse motion is no longer bound and instead tksheet relies on `<Enter>`  and `<Leave>` events. I am not 100% sure I will be able to do this however, I will update you here when I find out

**Comment by SamO6453** [comment]
Hello,


Thank you for replying! Yes, commented out the ("<Motion>", self, self.mouse_motion), in  _tksheet_main_table.py, resolved the lagging motion on cursor issue. Yeah, it stays or caught in that mouse_motion loop trying to do resizing a little too long.

Regards,
Sam

Sam Ouche
Optek – Validation/Verification Engineer
__________________________________
TT Electronics
2900 E. Plano Parkway, Suite 200, Plano, Texas 75074, U.S.A.
T: +1 972 323 2335  M: +1 214 287 1298
E: ***@***.******@***.***>

**Comment by ragardner** [comment]
Hey,

I've made a change in `6.3.5`. In previous versions `tksheet` would configure the cursor with every mouse motion, in `6.3.5` it checks the current cursor and only configures it if it needs to. However, I was unable to replace the mouse motion function

I also removed code which caused cursor change for header height and index width resizing from inside the main table, it is now slightly harder to align the cursor with their resizing lines

I am wondering if the constant calls to config the cursor were the reason it was ok under one OS and python version and not another

**Comment by SamO6453** [comment]
Great! I’ll update the tksheet lib to new version, 6.3.5 and test it.  Yes, I think the constant mouse motion event calls to resizing the cursor routine that causes this lagging. It will all add up delay on every pixel event changes and depending how fast the mouse changes position also while it’s in the call loop doing resize calculations and more event ques calls are pipeline; therefore, the update and redraw of cursor on new position is stuttering; I think and for not sure the intent or functionality of the mouse_motion() call and resizing is for.  I think there should be another flag or enable, click event to perform the resizing, not on every x, y coordination changes.  This would eat up the processing time..  thank you for updating the tksheet lib.

Regards,
Sam

Sam Ouche
Optek – Validation/Verification Engineer
__________________________________
TT Electronics
2900 E. Plano Parkway, Suite 200, Plano, Texas 75074, U.S.A.
T: +1 972 323 2335  M: +1 214 287 1298
E: ***@***.******@***.***>

**Comment by SamO6453** [comment]
Sorry, have you push the 6.3.5 version into the piwheels.org yet?  Or you can send me the link to the latest changes ver 6.3.5.  Thanks!

Regards,
Sam

Sam Ouche
Optek – Validation/Verification Engineer
__________________________________
TT Electronics
2900 E. Plano Parkway, Suite 200, Plano, Texas 75074, U.S.A.
T: +1 972 323 2335  M: +1 214 287 1298
E: ***@***.******@***.***>

**Comment by SamO6453** [comment]
NVM, I got it.  Thank you sir!

Regards,
Sam

Sam Ouche
Optek – Validation/Verification Engineer
__________________________________
TT Electronics
2900 E. Plano Parkway, Suite 200, Plano, Texas 75074, U.S.A.
T: +1 972 323 2335  M: +1 214 287 1298
E: ***@***.******@***.***>

**Comment by SamO6453** [comment]
I’m getting the following error messages when I do “pip install tksheet –upgrade.”

(.venv_local) ***@***.***:~/Gerry3 $ pip install tksheet --upgrade
WARNING: Skipping /home/raspberry5/Gerry3/.venv_local/lib/python3.11/site-packages/tksheet-6.3.5.dist-info due to invalid metadata entry 'name'
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: tksheet in ./.venv_local/lib/python3.11/site-packages (6.3.4)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 97, in _iter_built_with_inserted
    candidate = func()

Regards,
Sam

Sam Ouche
Optek – Validation/Verification Engineer
__________________________________
TT Electronics
2900 E. Plano Parkway, Suite 200, Plano, Texas 75074, U.S.A.
T: +1 972 323 2335  M: +1 214 287 1298
E: ***@***.******@***.***>

**Comment by ragardner** [comment]
Hey,

> Sorry, have you push the 6.3.5 version into the piwheels.org yet?  Or you can send me the link to the latest changes ver 6.3.5.  Thanks!

It seems as though piwheels is automated, I cannot push new releases to it

> not sure the intent or functionality of the mouse_motion() call and resizing is for

Basically it just checks the position of the cursor and if it is above a resizing grid line then it changes the cursor into an arrow. If it is above a selected row or column then it changes into a hand. The reason I failed to replace this code with `"<Enter>"` and `"<Leave>"` events is that they weren't reliable, the cursor wasn't reliably changing back into a normal pointer after entering and leaving a grid line

> I’m getting the following error messages when I do “pip install tksheet –upgrade.”

Unfortunately I have no idea what this error means sorry. I don't think it's to do with tksheets setup code though as the only thing that was changed in `setup.py` was the version number

**Comment by SamO6453** [comment]
Hello,

Thank you for the feedback.

Ok, it makes sense for the checking of the cursor falling into the grid line to transform the cursor.

I’ll debug the pip install tksheet –upgrade on my side.  I even tried pip install tksheet==VERSION, but still show the same error failing message.  I’ll upgrade the pip itself.  Thank you!

Regards,
Sam

Sam Ouche
Optek – Validation/Verification Engineer
__________________________________
TT Electronics
2900 E. Plano Parkway, Suite 200, Plano, Texas 75074, U.S.A.
T: +1 972 323 2335  M: +1 214 287 1298
E: ***@***.******@***.***>

**Comment by SamO6453** [comment]
Hi,

Regarding the pip install tksheet==6.3.5 issue, I can do pip install to ver 6.3.4 or any older version just fine, but to install with ver 6.3.5, I’m getting invalid metadata entry ‘name’.   Do you know what this mean?

***@***.***

Regards,
Sam

Sam Ouche
Optek – Validation/Verification Engineer
__________________________________
TT Electronics
2900 E. Plano Parkway, Suite 200, Plano, Texas 75074, U.S.A.
T: +1 972 323 2335  M: +1 214 287 1298
E: ***@***.******@***.***>

**Comment by SamO6453** [comment]
Hello,

Starting fresh with new OS image, and the pip install gives this new message DEPRECATION: tksheet is being installed using the legacy ‘setup.py install’ method.  Here the entire message.  Hope this will help.

***@***.***

Regards,
Sam

Sam Ouche
Optek – Validation/Verification Engineer
__________________________________
TT Electronics
2900 E. Plano Parkway, Suite 200, Plano, Texas 75074, U.S.A.
T: +1 972 323 2335  M: +1 214 287 1298
E: ***@***.******@***.***>

**Comment by ragardner** [comment]
Thanks for letting me know! 

Versions 7+ now have the new `pyproject.toml` file

Cheers
