### ISSUE TITLE
The tabel font does not change.

### ISSUE THREAD

**Issue by kimshanghi** [ragardner/tksheet#210]
Sorry, but the table font setting is not possible due to the change from version 6.x to version 7.x.
In version 7.x, the index font and header font are changed, but the table font does not change from its default state no matter how much I change the settings. Of course, the table font does not change even if set according to the 7.x document.
I need your help. Thanks in advance. The code is as follows:

self.sheet_table = Sheet(right_frame2, headers=self.data_headers, height=832, width=510, row_height=39,
                                 column_width=119, align='center', header_bg='AntiqueWhite1', header_height=50,
                                 index_bg='AntiqueWhite1', font=('Arial', 12, 'bold'), index_font=('Arial', 11, 'bold'),
                                 header_font=('Arial', 11, 'bold'), show_x_scrollbar=False, show_y_scrollbar=False,
                                 table_bg='mint cream', top_left_bg='mint cream', empty_vertical=-1, empty_horizontal=0)

OS : windows 11,
python 12,
app : Pycharm

**Comment by ragardner** [comment]
Thank you very much for the report and I'm sorry it wasn't working,

It should be fixed now in version `7.0.5`
