### ISSUE TITLE
function "checkbox" in "other_classes.py" currently creates a dropdown instead of a checkbox

### ISSUE THREAD

**Issue by legandro-github** [ragardner/tksheet#235]
not more to add to the title
check other_classes.py [line 202](https://github.com/ragardner/tksheet/blob/c25542c6a9a1d493038972f4f07539ee4394e542/tksheet/other_classes.py#L202C1-L202C2)

**Comment by ragardner** [comment]
Thanks very much for pointing this out,

It's fixed in `7.2.11`
