### ISSUE TITLE
using the "Supr"/"Del" key in the same way as the "Backspace" key

### ISSUE THREAD

**Issue by fmerchan65** [ragardner/tksheet#247]
The users of my application use the numeric keypad a lot and to delete the contents of a cell they use "Supr"/"Del" key on the numeric keypad more than the "Backspace" key. After several hours of research and testing I have not found the way to do it in a tksheet table.

**Comment by ragardner** [comment]
I'm not sure I understand sorry, questions:

Is the binding:
- Super + Del
- Super OR Del
?

Currently:
- Pressing Del when a cell is selected and a cell editor is not already open clears the cell without opening an editor
- Pressing Del when characters are selected in an open cell editor deletes those characters

I am trying to follow the behavior of other spreadsheets and I'm not sure there's any other ways to do this with Del?

**Comment by fmerchan65** [comment]
Sorry for the initial explanation. Yes, I mean Del key binding. Could the behavior of this binding be changed in an open cell editor and it would run like backspace key ?. I mean, delete the character just before where the cursor is.

**Comment by ragardner** [comment]
Thanks for the reply,

As I went about making the change I realized that the tkinter text widget deletes the forward character when there is no selected text

So when there are no selections it currently has the default behavior of:
- Backspace - deletes backward character
- Delete key - deletes forward character

I have checked the behavior of Libre office and it seems the same there as well

Would you still like the option of overriding this behavior?

**Comment by fmerchan65** [comment]
You are right. It's ok the Del key current behavior. Thanks a lot !

**Comment by ragardner** [comment]
Hey, in case you're interested I added the following option in `7.2.15`:

In your sheet initialization you can use the parameter:

- `editor_del_key`

With the following arguments:

- "forward" - delete forward character - default behavior
- "backward" - delete backward character
- "" - unbound

e.g.
`my_sheet = Sheet(parent, editor_del_key="backward")`

You can also use the keyword argument with the `set_options()` function
