### ISSUE TITLE
Should percentage_formatter use percentage_to_str?

### ISSUE THREAD

**Issue by Poikilos** [ragardner/tksheet#251]
I am not sure if it is right, so this is a question. I'm not sure if anything needs to be changed. Close if not.

Currently, percentage_formatter uses:
```Python
        format_function=format_function,
        to_str_function=to_str_function,
```
I'm not sure if/when `percentage_to_str` should be involved.

**Comment by ragardner** [comment]
Hello,

I think this part is okay, but thanks for inquiring. The `to_str_function` is the parameter above and it seems the function `percentage_to_str` is the argument used by default

```python
sheet.format("A", formatter_options=percentage_formatter(nullable=False))
```

Kind regards
