### ISSUE TITLE
how to change cell background colour when editing it ? I don't find the right set_options

### ISSUE THREAD

**Issue by fmerchan65** [ragardner/tksheet#255]
I have defined this table and the bg colour when editing the cell is white like the fg and I cannot see what I am writing. How can I change the bg or fg colour when editing a cell ? 

       self.sheet_facturas = Sheet(contenedor_pedido,
                        page_up_down_select_row = True,
                        startup_select = (0,1,"rows"),
                        data = [], 
                        headers = lista_campos,
                        total_rows = 20, 
                        total_columns = 16,
                        height = 400, 
                        width = 1780, 
                        font = ("Times Roman", 9, "normal"),
                        edit_cell_return='right'
                        )
       
        self.sheet_facturas.set_options(header_bg="#060c32")
        self.sheet_facturas.set_options(header_fg="white")
        self.sheet_facturas.set_options(header_selected_cells_bg="#060c32")
        self.sheet_facturas.set_options(header_selected_cells_fg="white")
        self.sheet_facturas.set_options(table_fg="white")
        self.sheet_facturas.set_options(table_selected_rows_bg="#757578")
        self.sheet_facturas.set_options(tab_bindings = ['<Tab>', '<Return>'])
        self.sheet_facturas.enable_bindings("single_select", "row_select", "arrowkeys", "copy", "paste", "undo", "edit_cell")

        self.sheet_facturas.pack(side=LEFT, ancho="nw", fill=tb.X)
        self.sheet_facturas.extra_bindings("begin_edit_cell", self.begin_edit_cell)
        self.sheet_facturas.edit_validation(self.validate_edits)
        self.sheet_facturas.extra_bindings("end_edit_cell", lambda event: self.rellenar_datos(event, None))
        self.sheet_facturas.extra_bindings([("all_select_events", self.sheet_select_event)])
        self.sheet_facturas.bind("<Double-1>", self.on_double_click)
        self.sheet_facturas.bind("<Button-3>", self.on_right_click)
        
        self.sheet_facturas.column_width(column = 0, width = 80)
        self.sheet_facturas.column_width(column = 1, width = 150)
        self.sheet_facturas.column_width(column = 2, width = 70)
        self.sheet_facturas.column_width(column = 3, width = 500)
        self.sheet_facturas.column_width(column = 4, width = 100)
        self.sheet_facturas.column_width(column = 5, width = 150)
        self.sheet_facturas.column_width(column = 6, width = 150)
        self.sheet_facturas.column_width(column = 7, width = 150)
        self.sheet_facturas.column_width(column = 8, width = 100)
        self.sheet_facturas.column_width(column = 9, width = 100)
        self.sheet_facturas.column_width(column = 10, width = 400)
        self.sheet_facturas.column_width(column = 11, width = 300)
        self.sheet_facturas.column_width(column = 12, width = 70)
        self.sheet_facturas.column_width(column = 13, width = 50)
        self.sheet_facturas.column_width(column = 14, width = 600)
        self.sheet_facturas.column_width(column = 15, width = 150)
        
        self.sheet_facturas.checkbox_column(c = 12)
        self.sheet_facturas.checkbox_column(c = 13, check_function=lambda event: self.calcular_totales(event, None))
        
        self.sheet_facturas.align_columns([3,6,7,8], 'center')
        self.sheet_facturas.align_columns([0,1,2,4,5,15], 'right')
        self.sheet_facturas.highlight_columns([5,10,11,15], highlight_header=False, bg="#304864")
        self.sheet_facturas.readonly_columns([5,10,11,15])

**Comment by ragardner** [comment]
Hello,

This option doesn't currently exist but it is controlled by this line:

```python
bg, fg = self.PAR.ops.table_bg, self.PAR.ops.table_fg
```

in the file `main_table.py`

And similar lines in the files `row_index.py` and `column_headers.py` for the index and header cell editors if you use those

I will have to add overrides in a future release

Kind regards

**Comment by ragardner** [comment]
I have added the following `Sheet()` parameters, also available for `set_options()` function in version `7.2.23`:
- `table_editor_bg`
- `table_editor_fg`
- `table_editor_select_bg`
- `table_editor_select_fg`
- `index_editor_bg`
- `index_editor_fg`
- `index_editor_select_bg`
- `index_editor_select_fg`
- `header_editor_bg`
- `header_editor_fg`
- `header_editor_select_bg`
- `header_editor_select_fg`

They change both the text editor and the dropdown colors

**Comment by fmerchan65** [comment]
Perfect !. It runs ok. Thanks a lot !.
