### ISSUE TITLE
MainTable.insert_col_rc when not all_columns_displayed

### ISSUE THREAD

**Issue by PatLechevallier** [ragardner/tksheet#26]
https://github.com/ragardner/tksheet/blob/b9c27d9b15b6865ac5c3805b22d20273693884d3/tksheet/_tksheet_main_table.py#L2518

Good Day,

Please see the attached line code.

I want to display a sheet of 5 columns, hence I call: display_columns([0,1,2,3,4])
If I call MainTable.insert_col_rc with anything selected == True, I expect that it adds a column at the last position and displays it if I am not wrong.
But at this line code and the one after, it seems to hide the last column and add 2 columns:
 display_columns() == [0,1,2,3,5,6]

Let me know if I am wrong, this line code shifts by one the positions.

Best Regards and Thank you for your amazing work

**Comment by ragardner** [comment]
Hello and thanks for your interest in the library, I am sorry for the lack of documentation at the moment

If I understand you correctly; you simply want to create a new table with 5 columns, to do this on start up you would do
```python
my_sheet = Sheet(<parent widget goes here>, total_rows = <integer of chosen number of rows>, total_columns = 5)
```

or to set it to 5 columns after initialization you can use
```python
my_sheet.total_columns(5)
```

The function `display_columns()` is only used to display a subset of the existing columns

Also, the functions inside `_tksheet_main_table.py` are internal functions and `insert_col_rc()` is used internally after the user right clicks on a column and selects insert columns

These internal functions generally shouldn't be used by the developer as they are just utilized by the program

The functions you can use on your `Sheet()` widget are contained in the file `_tksheet.py`, it should contain every function needed to view and modify your sheet and its data

**Comment by PatLechevallier** [comment]
Thanks for your answer!

To give more details, I am creating a Sheet() by giving a list of list with existing data let's say with 5 columns.
I am actually using display_columns() to effectively display a subset of the existing columns.
I am concern that when I hide a column and insert a column at the end, the displayed_column is not correct as it goes from [0,1,2,3,4] to [0,1,2,3,5,6]

Basically, I am implementing a feature to hide a column properly and be able to do all rthe otehr actions I want,m especially from the right_click

**Comment by ragardner** [comment]
@PatLechevallier Ok thanks for the clarification I will look into this and get back to you

**Comment by ragardner** [comment]
@PatLechevallier There was indeed a bug and thank you for finding it, it should be fixed with version `4.9.0`, here are the release notes:

### Version 4.8.9 - 4.9.0
 - Make functions `insert_row()`, `insert_column()`, `delete_row()`, `delete_column()` adjust highlighted cells/rows/columns to maintain correct highlight indexes
 - Built in right click functions now also auto-update highlighted cells/rows/columns
 - Add argument `reset_highlights` to `set_sheet_data()` default is `False`
 - Add function `dehighlight_all()`
 - Various bug fixes
 - Right click insert column when hiding columns has been changed to always insert fresh new columns

**Comment by ragardner** [comment]
@PatLechevallier O sorry, I only just read your edit, I am actually working on having hide and show columns functionality on right click myself but I'm afraid I can't give you a solid time frame on when it will be finished

I think for the `display_columns()` function I like it the way it currently is but the hide/show columns stuff I am working on does utilize the `self.displayed_columns` variable as well

**Comment by PatLechevallier** [comment]
@ragardner Thank You! It works well.

I'll wait for your feature. 
Unfortunately, I also need to have the accurate coordinates of the cells, hence the columns:
I have noticed when anything_selected and not all displayed, the stidx is set as the total_columns()
So the index if the inserted column is total_columns()+1.
If I start with [0,1,2,3,4,5] and insert at 4, I will have [0,1,2,3,6,4,5]

I would rather have a shift but It may not respect the spirit of your implementation.
In that case, I will do a workaround.

And by the way, If I reset all_column_displayed to true after having hidden columns and insert a column, it sorts the displayed columns as [0,1,2,3,4,5,6] and display the inserted one at the end.

Best Regards

**Comment by ragardner** [comment]
@PatLechevallier 

> And by the way, If I reset all_column_displayed to true after having hidden columns and insert a column, it sorts the displayed columns as [0,1,2,3,4,5,6] and display the inserted one at the end.

I'm interested in fixing this if there's an issue, if it's not too much trouble can I ask are you simply setting the variable `all_columns_displayed` to `True` or are you using the function `display_columns(enable = False)` to set it?

It seems to me that there may be issues with the `self.column_positions` variable if you simply set `all_columns_displayed` to `True` without using the function

Thank you

**Comment by PatLechevallier** [comment]
No problem. I only and always use the function like this `display_columns(indexes=[..], enable=True, deselect_all = False)` or `display_columns(enable=False, deselect_all = False)`

I manage to do the workaround, so no worries.
