### ISSUE TITLE
Updating numbers in cells.

### ISSUE THREAD

**Issue by 123Inge** [ragardner/tksheet#29]
Hi. 
First of all, I really what you have made here, and using it for a project. By far the best solution I have found to display data in a table for tkinter.

But I have a problem with updating a given number in the table. I have a database, where information about a set products are stored. When one products is updated in the database, a number in the table should be updated, and display the updated number. But this does not happen. The number is updated in the database, and I can see, via the terminal, that the number is updated, but it is not disaplayed. If I stop the program and then start it again, the updated number is displayed. To update cells, I used sheet.set_cell_data(?, ?, ?). Do you have any ideas on what I could do to solve this. 

In advance thanks. 
Kind regards, 123inge.

**Comment by ragardner** [comment]
Hello,

You might need to use
`sheet.refresh()`
everytime after using 
`sheet.set_cell_data(?, ?, ?)`

Let me know if this works or not

**Comment by 123Inge** [comment]
This worked. Now the number is updated on the screen.
Thank you very much!

- 123inge
