### ISSUE TITLE
Editing the row index?

### ISSUE THREAD

**Issue by alvferhid** [ragardner/tksheet#3]
First of all, thank you for creating this widget! I'm still a big noob, I just started coding less than 6 months ago and this is just perfect of an appointments app I'm creating for a dentist clinic. The only thing I'd like to know is if I can find documentation about if it's possible to edit the row index because I want to change them from "1","2","3"... to display hours, but doesn't matter what I do, I can't edit it. 

Thank you so much and sorry if I'm asking something too stupid.

**Comment by ragardner** [comment]
Unfortunately at the moment you cannot directly edit the row index once your program is running, like you would a cell... BUT! You can get your program to display something else in the row index by using the function `row_index()` on your tksheet widget

To get one of your columns to show in the row index you can use an integer representing the position of the column you want to show, e.g. the first column would be 0 the second column would be 1

`mysheet.row_index(new_index = 0)`

To put a completely new set of values in the row index you can use the same command but with a different argument which accepts Python lists or tuples like so:

`mysheet.row_index(index = ["my row index values example 1", "my row index values example 2"])`
