### ISSUE TITLE
Ctrl_V of 1 Column removes empty rows

### ISSUE THREAD

**Issue by PatLechevallier** [ragardner/tksheet#30]
Good Day,

Me again~

https://github.com/ragardner/tksheet/blob/2c202864934f7fa48b356d1eb7ddd925c7f25039/tksheet/_tksheet_main_table.py#L540-L555

When I copy 1 column and paste it to another one, the empty rows are removed, so it goes up the rows with values on top.
Same when I copy 2 columns.

The line 550 `nd.append(r[:len(r) - next(i for i, c in enumerate(reversed(r)) if c)]) ` that raise  the exception `StopIteration`. Is it the behavior intended? 

Best Regards

**Comment by ragardner** [comment]
Yea this is the incorrect behavior, I have changed it in `4.9.3` hopefully it works like other spreadsheets now
