### ISSUE TITLE
Right alignment for value fields

### ISSUE THREAD

**Issue by nosklo** [ragardner/tksheet#31]
Hi, I'm using `tksheet `and I really like it, thanks for all the effort you've put into it.

In this application I'm developing, I need the value columns to be right-aligned so that the decimal fields align - it is essential for my users to see the values aligned to avoid mistakes.

I believe tksheet doesn't support right alignment currently, and alignment changes are global. I want to implement right-alignment and only for some select columns, not the entire sheet.

Is this something you plan on implementing? Can I help somehow?

Alternatively, can you give me some code insights and hints on where/how to implement it myself?

**Comment by ragardner** [comment]
@nosklo Hi there,

Thanks for your interest in the library,

I have completed working on right hand cell alignments for the main table, not for the header or index yet

Here's how you set individual alignments:
```python
self.sheet.align_cells(row = 1, column = 1, align = "e")
self.sheet.align_rows(rows = 3, align = "e")
self.sheet.align_columns(columns = 4, align = "e")
```

You can also set the alignment globally to "e" if needed

Let me know if there are any issues

Release notes:
### Version 4.9.4
 - Make `display_subset_of_columns()` and other names of the same function always sort the showing columns
 - Make right click insert columns left shift data columns along
 - Fix issues with `insert_column()`/`insert_columns()` when hiding columns
 - Add default arguments `mod_column_positions` to functions `insert_column()`/`insert_columns()` which when set to `False` only changes data, not number of showing columns
 - Add `"e"` aka right hand side text alignment for main table, have not added to header or index yet
 - Add functions `align_cells()`, `align_rows()`, `align_columns()`

**Comment by nosklo** [comment]
Wow that's great, it solves my use case. Thanks for the prompt response!
