### ISSUE TITLE
[Proposal] Please add readonly columns and cells if possible

### ISSUE THREAD

**Issue by lmcdd** [ragardner/tksheet#33]
Love and kindness to you =)

PS: I've added this in my local fork, but I think I wrote bad code...

**Comment by ragardner** [comment]
You can make it so cells are read only by not using certain bindings

Don't use `enable_bindings()` or `enable_bindings("all")` because this will enable all the sheets functionality

This is a list of the existing bindings

```python
self.sheet.enable_bindings(("single_select", #"single_select" or "toggle_select"
                                         "drag_select",   #enables shift click selection as well
                                         "column_drag_and_drop",
                                         "row_drag_and_drop",
                                         "column_select",
                                         "row_select",
                                         "column_width_resize",
                                         "double_click_column_resize",
                                         "row_width_resize",
                                         "column_height_resize",
                                         "arrowkeys",
                                         "row_height_resize",
                                         "double_click_row_resize",
                                         "right_click_popup_menu",
                                         "rc_select",
                                         "rc_insert_column",
                                         "rc_delete_column",
                                         "rc_insert_row",
                                         "rc_delete_row",
                                         "copy",
                                         "cut",
                                         "paste",
                                         "delete",
                                         "undo",
                                         "edit_cell"))
```

If you don't even want the user to be able to select cells or columns etc then don't use `enable_bindings()` at all, else you can pick whichever bindings you want to enable and use them with the above function like so

If you want to disable scrolling and clicking events from occurring internally you can use `basic_bindings(False)`

If this doesn't answer your question let me know

**Comment by lmcdd** [comment]
Thank you for your answer, but I think this is not exactly what I need, I want specific columns to block for editing, not all.

my shit code =)
https://github.com/lmcdd/tksheet/commit/d4f5367b5b2dd17153d43880e5e7353fbf71981c

**Comment by ragardner** [comment]
Oh I see, thanks for the suggestion, I will add this to my to do list, cannot give you a time scale though

**Comment by lmcdd** [comment]
Thank You =)

**Comment by ragardner** [comment]
@lmcdd I have added readonly cells/columns/rows in `4.9.7` 

use like so 
```python
self.sheet.readonly_columns(4)
self.sheet.readonly_rows(4)
self.sheet.readonly_cells(0, 0)
```
you can also use a list of indexes

use argument `readonly = False` to enable editing again

note that I don't think it currently blocks dropdowns

let me know if it works correctly

**Comment by lmcdd** [comment]
@ragardner, works great, thank you!
