### ISSUE TITLE
[BUG] takes the value of a hidden cell when editing a cell that has replaced it

### ISSUE THREAD

**Issue by lmcdd** [ragardner/tksheet#35]
![Peek 2020-08-09 21-53](https://user-images.githubusercontent.com/6673326/89739724-c940d500-da8b-11ea-96d7-e9251eb7c8e0.gif)

Automatically substitutes a value from the first column (hidden).

**Comment by ragardner** [comment]
Sorry for the bug, it should be fixed in `4.9.7`

**Comment by lmcdd** [comment]
Great, thank you, everything is fine now.
