### ISSUE TITLE
Bind Tab Key on Text Editor

### ISSUE THREAD

**Issue by PatLechevallier** [ragardner/tksheet#37]
https://github.com/ragardner/tksheet/blob/17ed5d4b6b59488ea6d8c7e5ff6fcb441adb8b8f/tksheet/_tksheet_main_table.py#L4212-L4215

Good Day,

On Excel, `<Tab>` key is bound like `<Return>+<Right>`. It validates and moves to the next right cell.
I'd like to add it at the creation of the text editor when the edit cell start.

In a more generic way, can we just add the possibility of binding other keys on the text editor?
If it already exists please tell me how to do such.

Best Regards

**Comment by ragardner** [comment]
It should be added in `4.9.7` but try it out and let me know if it's not working correctly

**Comment by ragardner** [comment]
@PatLechevallier  

Regarding 
> In a more generic way, can we just add the possibility of binding other keys on the text editor?

I added the below code in version `4.9.7`

```python
def bind_key_text_editor(self, key, function):
    self.MT.text_editor_user_bound_keys[key] = function

def unbind_key_text_editor(self, key):
    if key == "all":
        for key in self.MT.text_editor_user_bound_keys:
            try:
                self.MT.text_editor.textedit.unbind(key)
            except:
                pass
        self.MT.text_editor_user_bound_keys = {}
    else:
        if key in self.MT.text_editor_user_bound_keys:
            del self.MT.text_editor_user_bound_keys[key]
        try:
            self.MT.text_editor.textedit.unbind(key)
        except:
            pass
```

It's not perfect though because you can't really bind keys to the text widgets actual functions, I might add this functionality later, but I can't give you a time frame sorry

**Comment by PatLechevallier** [comment]
The functionality for the event `<Tab>` is working fine. 👍 
No worries, it's not a priority.
