### ISSUE TITLE
Ctrl_V of Text with Retun Carriage Using an object defining __str__

### ISSUE THREAD

**Issue by PatLechevallier** [ragardner/tksheet#39]
https://github.com/ragardner/tksheet/blob/e70ca2af5b8a60cc464a99a8ecb5e806e386c136/tksheet/_tksheet_main_table.py#L3459-L3523

Good Day,

I am actually using an object as a cell content that has a `__str__` defined method.

The problem is when I type a text with `\n`, it doesn't display correctly the text.
When I press `<Return>` the displayed box has the right height but the text itself is shifted up by few pixels (I would say 5).

But here is the point of this ticket:
When I copy the text to another cell, the box doesn't change its size and the displayed text goes out of the box.
My guess is Line 3467, `lns` can only contains one string and is not consistent with L3465 where it's splitted by `\n`.
Hence, Line 3492 is always false.

I am a bit struggling facing those two issues, I think both problems are of the same nature, But for Now I have only found the Ctrl_V issue.
I would appreciate your help very much.

Best Regards

**Comment by ragardner** [comment]
Hello,

Thanks for the report,

I am currently working on a new update which will address all of the current issues, I will look into this one as well

It shouldn't be longer than a couple of days

**Comment by ragardner** [comment]
FYI
I think I have recreated the issue
![image](https://user-images.githubusercontent.com/26602401/91168160-113b3b00-e6cd-11ea-8024-b2117166b35e.png)

```python
class hello:
    def __init__(self):
        self.x = True

    def __str__(self):
        return "hello class\ntest"
```

**Comment by ragardner** [comment]
Sorry for the spam but I think I have found a fix for the issue if you want to implement it yourself in the mean time, the logic was incorrect, as you pointed out for objects with a `str` method which contains a newline,

This is the fixed code
```python
if isinstance(lns, str):
    lns = lns.split("\n")
else:
    lns = f"{lns}".split("\n")
```

**Comment by PatLechevallier** [comment]
Re,

Perfect! It's what I did for this line 👍 
Oh and yes I forgot, that it's in the `main_table_redraw_grid_and_text` so it should solve both problems, my bad.
