### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by kglasnapp** [ragardner/tksheet#4]
This widget is very nice keep up the good work. I want to use it in a tool I am making. Note I am a newbie to tkinter. Is is possible to call one of my functions when the user say selects row?

**Comment by ragardner** [comment]
Thanks!

I have just now updated the library with new separate responses for different selection events and a new demo showing how to add bindings, the demo can be found in the README.md or tests folder, using the demo you'll be able to see the responses that are sent to your bound functions

The full list of `extra_bindings()` can be found inside `_tksheet.py` in the `extra_bindings()` function

There is one thing I am possibly unsure about the current system and that is the drag selection events, currently every time the user drags the mouse selecting cells, rows or columns a response is sent, so it's possibly a bit inefficient and I might change it in the future, or might not

I also might separate out enable shift select from drag selection to give better control over what the user can do

I still have to get around to writing full documentation also

Let me know if you have any more questions or how you get on using it

**Comment by kglasnapp** [comment]
Thanks so very much – the changes work exactly as I wanted it. 

 

I am just starting to use the tool but so far it looks great. Great job.

 

I am really impressed with the speed of the tool. I will keep you informed of my progress.


Keith
