### ISSUE TITLE
[Proposal] ability to display Boolean values as checkboxes.

### ISSUE THREAD

**Issue by lmcdd** [ragardner/tksheet#41]
![изображение](https://user-images.githubusercontent.com/6673326/91328680-e4bc1780-e7cf-11ea-8f8a-512ed71ff341.png)

**Comment by fpp-gh** [comment]
Hello,

I second this proposal by mlcdd on my birthday last year :-)
tksheet is really, really impressive, but not always easy to grok...
If there is a proper way to insert checkboxes in cells, I'd really appreciate a howto :-)
TIA,
fp

**Comment by fpp-gh** [comment]
Also, alternate line background colours ? :-)

**Comment by fpp-gh** [comment]
BTW, why do all the *.py files under tksheet/tksheet have only HTML content ?...

**Comment by ragardner** [comment]
@fpp-gh Hello,

I am going to stop working on this repository very shortly, all I really want to do is add a bit to the documentation, part of this has to do with how little I will be working with tkinter in the future

For a checkbox quick work around you could use cell highlights with a green color for check and red for not and then bind mouse button 1 to a function that checks which column the user clicked on to change the color, to get the status of the box you could use `sheet.MT.cell_options[(row int, column int)]['highlight'][0] == "my green color"` which would return `True` if checked green

> BTW, why do all the *.py files under tksheet/tksheet have only HTML content ?...

I am not sure what you mean by this, all i can see is python code, can you provide an example?

**Comment by fpp-gh** [comment]
@ragardner 

Thanks for the feedback, but that is really too bad : tksheet really has a lot of potential, and I've done lots of (simpler) stuff in tkinter in the past.
More docs can't hurt though  :-) 
As for the files, I must have been asleep at the wheel for a moment : I downloaded them with right-click/save, which must have pulled the pages's HTML code :-) 
The files in site-packages are the actual python code though.
And I'll try your checkbox workaround, thanks for that !
Best,
fp

**Comment by paljsingh** [comment]
+1
I too have the same requirement to have checkboxes (and buttons if possible) in tksheet. 
As a quick workaround, for now I 'll be sticking to unicode text (☑ or ✓ for checked, ☒ or ☐ for unchecked) 
in tksheet cells and add event handlers to switch between the two.

**Comment by ragardner** [comment]
I have finished the code for check boxes, here's an image below (colors changed by using highlight cells), documentation here:
https://github.com/ragardner/tksheet/blob/master/DOCUMENTATION.md#21-check-boxes
![checkboxes](https://user-images.githubusercontent.com/26602401/139532258-d9e0672b-ad58-4d3b-bf49-fb37c24a807e.png)

**Comment by fpp-gh** [comment]
Nice, will test this, thanks much !
best,
fp
