### ISSUE TITLE
<MouseWheel> on Linux

### ISSUE THREAD

**Issue by skedus** [ragardner/tksheet#42]
Hi,
For information, I notice that binding to mouse wheel does not work on Linux, because for mouse wheel:
- Windows, Mac: Binding to `<MouseWheel>` is being used
- Linux: Binding to `<Button-4>` and `<Button-5>` is being used

I added in your code, bellow binding `<MouseWheel>`:

            self.bind("<MouseWheel>", self.mousewheel)
            self.bind("<Button-4>", self.mousewheel)
            self.bind("<Button-5>", self.mousewheel)

            self.unbind("<MouseWheel>")
            self.unbind("<Button-4>")
            self.unbind("<Button-5>")

And it is working as expected on Linux
Have a nice day

**Comment by ragardner** [comment]
Yes you're right, the bindings are different under Linux, will try to get this fix included in next version

thanks

**Comment by skedus** [comment]
Thank you ;-)

**Comment by ragardner** [comment]
You can try out the fix in I added `4.9.9` if you want to

**Comment by skedus** [comment]
Hi,
code in `_tksheet_main_table.py` is correct for Linux into  `basic_bindings` function but it does not work with 4.9.9

I was using 4.9.1 and it seems that function `mousewheel ` has changed from 4.9.9

I tested with the old `mousewheel ` function and it is OK

mousewheel 4.9.1:
https://github.com/ragardner/tksheet/blob/b1e277df52a38e8938c38fc1c220b0bf50969704/tksheet/_tksheet_main_table.py#L2222

**Comment by skedus** [comment]
as you added platform detection it could be temporally (quick fix) a linux binding to `mousewheel_linux ` which is the old function ? and the new `mousewheel` one for windows ? 
may be you do not have the possibility to test on linux ?

**Comment by ragardner** [comment]
@skedus 

Sorry about that, it must be the `event.num` hopefully it works for you in `4.9.92`

**Comment by skedus** [comment]
Hi @ragardner 
Thank you for your quick answer :-)
Well,  it does not work yet (for some reason enum.delta is always 0 on linux)

Here is the code modification which is working: simple elif instead of if

```
def mousewheel(self, event = None):
         if event.delta < 0 or event.num == 5:
             self.yview_scroll(1, "units")
             self.RI.yview_scroll(1, "units")
         elif event.delta >= 0 or event.num == 4:
             if self.canvasy(0) <= 0:
                 return
             self.yview_scroll(-1, "units")
             self.RI.yview_scroll(-1, "units")
         self.main_table_redraw_grid_and_text(redraw_row_index = True)
```
 
I added as well `shift_mousewheel` using your code for mousewheel into `basic_bindings` function as following (with the unbind too)

```
            if USER_OS == "Linux":
                for canvas in (self, self.CH):
                    canvas.bind("<Shift-Button-4>", self.shift_mousewheel)
                    canvas.bind("<Shift-Button-5>", self.shift_mousewheel)
```

and modify `shift_mousewheel `function as following with elif as well and move event.num == 4 with elif

```
    def shift_mousewheel(self, event = None):
        if event.delta < 0 or event.num == 5:
            self.xview_scroll(1, "units")
            self.CH.xview_scroll(1, "units")
        elif event.delta >= 0 or event.num == 4:
            if self.canvasx(0) <= 0:
                return
            self.xview_scroll(-1, "units")
            self.CH.xview_scroll(-1, "units")
        self.main_table_redraw_grid_and_text(redraw_header = True)

```

And it is working well, if you can introduce those modifications that would be great
Thanks

**Comment by ragardner** [comment]
Sorry about that, they have been introduced in `4.9.93` and yeah, I don't have access to Linux at the moment, need to install to 2nd hard drive at some point

**Comment by skedus** [comment]
Yes  all is OK now with 4.9.94 
Thank you very much :-)
