### ISSUE TITLE
[Proposal] Disable auto size to text or Cells to keep their dimensions if resized by the user

### ISSUE THREAD

**Issue by PatLechevallier** [ragardner/tksheet#43]
Hi,

I am pasting a lot of text inside one cell (especially with `\n`), and I usually don't need to display it.

There is Three levels in this proposal:

1. Disable auto size to text: at least when we edit not the cell itself but a cell of the same Row
2. Disable auto size to text: always, as a config of the Sheet
3. Keep the dimensions if Row Height or Column Width has been set manually by the user: that implies to keep the dimensions of the specifics RowIndex and ColumnHeader somehow

**Comment by ragardner** [comment]
Hello,

Quick question,

Is this just for after the cell edit is completed? Such as a resize that occurs after pressing the Return key

**Comment by PatLechevallier** [comment]
Re,

Yes absolutely.
After pressing Return on the cell itself or a cell of the same Row.

**Comment by ragardner** [comment]
I can possibly do your suggestion of cells resized by the user in the future, but in the mean time I have added an option to disable auto resize after editing

### Version 4.9.9
 - Attempt to fix Linux mousewheel scrolling
 - Add `enable_edit_cell_auto_resize` option to startup and `set_options` default is `True`

**Comment by PatLechevallier** [comment]
Hi!

Thanks for the quick implement 👍 
Would it be relevant to add the if statement also here?
At Line 4445

https://github.com/ragardner/tksheet/blob/12db51bea4e1315ed2b5472d1dcf0ba68518c640/tksheet/_tksheet_main_table.py#L4438-L4447

So it won't resize at the begin edit cell.

**Comment by ragardner** [comment]
Yes you're right, should be fixed in `4.9.91`

**Comment by PatLechevallier** [comment]
Re,

Thanks. It's working well.
