### ISSUE TITLE
[Question/Proposal] Expand columns by expanding window (X axis)

### ISSUE THREAD

**Issue by VarunS2002** [ragardner/tksheet#45]
If I have a fixed number of columns, is it possible to expand the columns proportionally when I expand the main window by the x axis? Basically mimicking the tkinter `.columnconfigure` method for frames and widgets.
Example: 
![demo_tksheet](https://user-images.githubusercontent.com/30069380/92221579-51fc3680-eebb-11ea-8265-6cc52224ed95.gif)
In this program you can see that the bottom labels expand proportionally but the columns of the tksheet Sheet don't .
Code I used for the bottom frame having the labels:
`bottom_frame.columnconfigure(0, weight=1)` for each column of the grid.

**Comment by ragardner** [comment]
Sorry for the delay in my response,

I might eventually get around to adding this but unfortunately I have limited time and have to prioritize, if you need this functionality soon you might need to add it yourself by adding a new function in `tksheet_main_table.py` and making the `<Configure>" binding on line 279 direct to that function
