### ISSUE TITLE
insert row doesn't appear when used on already visible sheet

### ISSUE THREAD

**Issue by JamesGKent** [ragardner/tksheet#46]
in my application I don't have all the info to go onto the sheet at the time I create the sheet, instead I am populating it on the fly as my results become available (anywhere from 30 seconds to 15 minutes to get all rows)

unfortunately any rows added are not visible initially, it appears that there is no trigger to re render. this means that if I scroll after adding a row it becomes visible.

I think the best way to solve this would be to add a member variable to the Sheet class and a new handler:
```
class Sheet:
    __init__(...):
        self.after_insert_id = None
    after_insert(self):
        self.refresh()
        self.after_insert_id = None
```

then for each type of insert handler:
```
    insert_row(self, ...):
        ...
        if self.after_insert_id is None:
            self.after_insert_id = self.after_idle(self.after_insert)
```

this way no time is wasted updating the display while you're actively adding things to the sheet, but as soon as we're done a refresh is triggered

**Comment by JamesGKent** [comment]
i should probably add that while this helps if your data is being generated in the main thread (i.e. where mainloop runs) this doesn't help once threading is involved as then its always idle. in which case I changed the above  to a normal `after` call with a 100ms timeout. this may be beneficial to offer as an option

**Comment by ragardner** [comment]
Hm, yes thanks, this seems like a good idea, would a standard after call with the variable check be okay as enabled by default? and you think 100ms would be an appropriate time?

**Comment by JamesGKent** [comment]
for me a standard after call worked better and would allow people to tailor to their own needs, are you thinking additional arguments to the constructor for this or a function to set this behavior up?

**Comment by ragardner** [comment]
It should be working in `4.9.95` give it a go and let me know if something isn't right

**Comment by JamesGKent** [comment]
this looks good, a few comments though:

1. why have you wrapped every call to `after` in a `try: except:` block? I've never ever seen this call fail as it only queues an event to happen and a `try: except` without a specific exception class isn't very clean.
2. would it not be better to use an instance variable set to 100ms by default rather than hard coding it everywhere used?

**Comment by ragardner** [comment]
Thanks for your comments,

I used `try` because I recalled scenarios in the past where the window had been destroyed and after was called resulting in an error which froze the program and prevented it from closing properly

Yeah good point about the variable, will change soon

**Comment by ragardner** [comment]
@JamesGKent 

I have removed the tries and made the ms a variable, version notes:

### Version 4.9.96
 - Fix bug with dragging scrollbar when columns are shorter than window
 - Add startup argument `after_redraw_time_ms` default is `100`
