### ISSUE TITLE
Blank column bug?

### ISSUE THREAD

**Issue by UnsignedArduino** [ragardner/tksheet#48]
First of all, I would like to thank you for this amazing library. It's _amazing_. Period. (It can render 1114111 columns with no problem, albeit 2 rows)

There seems to be a bug in where this is a blank column to the left of the first user-defined column. Using the scrollbar even though it isn't "active" (grayed out) when the window is bigger than the table width-wise will cause an extra column to appear. 

Here is a zip of the video: (Sorry for the inconvenience of having to download and extract a file)
[tksheet bug.zip](https://github.com/ragardner/tksheet/files/5248985/tksheet.bug.zip)

**Comment by ragardner** [comment]
Thanks very much! and thank you for pointing out this bug, I will try to fix it and let you know when I have

**Comment by ragardner** [comment]
It should be fixed in `4.9.96`

**Comment by UnsignedArduino** [comment]
Thank you so much for your quick response! I can't wait!

(BTW, for some reason, the `height` parameter doesn't seen to work. Am I missing something simple, or should I open another issue?)

**Comment by ragardner** [comment]
The height currently won't work without also using a width, I couldn't work it out last time but I might give it another go

**Comment by UnsignedArduino** [comment]
Oh! Thank you! That's why! I'm currently making a GUI, and the table is slightly taller than everything else, so I had to make it shorter 😅

I'm going to close this since the bug has been fixed - thank you so much again! This is a great module that I would definitely agree with being in the standard library!
