### ISSUE TITLE
[Question] Is there anyway to fill border of cells as Excel did?

### ISSUE THREAD

**Issue by monretutiel** [ragardner/tksheet#49]
Hello, 

First of all, congratulations for your job. You are doing really well. 
I was wondering if there is anyway to make border at cells to be able to make tables.

Regards.

**Comment by ragardner** [comment]
There is currently not a way to make cell borders thicker or change their color sorry

**Comment by monretutiel** [comment]
I was thinking that maybe hiding the grid itself where is data should be enough for me, if you can tell how are you playing with grid I can take a look and maybe help with a method.
Regards.

**Comment by ragardner** [comment]
To hide the grid you can use arguments `show_vertical_grid = False` and `show_horizontal_grid = False` at startup or with the function `set_options()` e,g, `my_sheet.set_options(...`

**Comment by monretutiel** [comment]
OK, I will check it. But could I do it by cell?

**Comment by ragardner** [comment]
Sorry no, there is no way to change specific cell borders
