### ISSUE TITLE
working with large tables

### ISSUE THREAD

**Issue by vladon1984** [ragardner/tksheet#51]
Good afternoon!

Is it possible to fill the table using the parallel filling method. I need to display large arrays of tables from a database. Treeview Tkinter does not allow working with streams. Filling in the table takes 40 minutes.

**Comment by ragardner** [comment]
Hi there,

Sorry for the delay,

I am not sure what you mean by parallel filling but currently the only methods of adding to the table are:

Full sheet overwrite:
```python
sheet.set_sheet_data(<list of lists, sublists are rows>, verify = False)
```

Single row (`idx` argument is index of insert):
```python
sheet.insert_row(values = <list of values representing a row>, idx = 0)
```

Multiple rows as a list of lists (`idx` argument is index of insert):
```python
sheet.insert_rows(rows = <list of lists, sublists are rows OR an integer for number of empty rows>, idx = 0)
```

You can find these and other functions in both the readme and in the `_tksheet.py` file

If these aren't quite what you need then let me know
