### ISSUE TITLE
how can i use excel's data as data in tksheet?

### ISSUE THREAD

**Issue by feliperomeiro96** [ragardner/tksheet#52]
Hello, you are doing great in your job, congrats! 
 I would like to know if can i take my data in excel and display it on tksheet. following my path:
"C:/Users/Marcio Romeiro/Favorites/Desktop/Felipe/Apparatus/CDGN/dados_de_entrada.xls"

**Comment by bnxvs** [comment]
You could to use pandas library to read excel file to dataframe. So, then you could convert dataframe to a list, with values.tolist() method.

```
from tkinter import messagebox
from tkinter.filedialog import askopenfilename
from tksheet import Sheet
import pandas as pd

data = askopenfilename(filetypes=(('Excel files', '*.xlsx'),))
    if data == '':
        messagebox.showwarning(title='Warning!', message='Nothing to import. Please, choose a file!')
    else:
        tb = pd.read_excel(data, header=None)
        table_data = tb.values.tolist()
```

And, then use: **table_input.set_sheet_data(table_data)** and **table_input.redraw()**
That's all.

**Comment by ragardner** [comment]
@feliperomeiro96 I am sorry for the very late reply,

I have included in the documentation which I have started writing a short example of using `pandas` to open an excel file

You can find it here: https://github.com/ragardner/tksheet/blob/master/DOCUMENTATION.md#Example-Loading-Data-from-Excel
