### ISSUE TITLE
Incorrect working Sheet.delete_row()

### ISSUE THREAD

**Issue by bnxvs** [ragardner/tksheet#54]
Before program delete
![Снимок экрана 2021-02-06 в 19 52 22](https://user-images.githubusercontent.com/49068521/107119975-078d4480-68b5-11eb-86cc-58c177b09c98.png)
After program delete (with default options)
![Снимок экрана 2021-02-06 в 19 52 30](https://user-images.githubusercontent.com/49068521/107119977-09ef9e80-68b5-11eb-9db3-64a2f6342ea7.png)

**Comment by ragardner** [comment]
Sorry about that

I made a quick fix in 4.9.97 (defaults to deleting first row) but to look at why the error occurred with index `-1` and fix will take me a bit longer

**Comment by bnxvs** [comment]
No problem. Great product. Thanks for your work.

**Comment by bnxvs** [comment]
Thank you!
