### ISSUE TITLE
Unexpected Exception on get_dropdown_value

### ISSUE THREAD

**Issue by skedus** [ragardner/tksheet#56]
Hi,
I found an unexpected exeption:
Exception in Tkinter callback
Traceback (most recent call last):
  File "...AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "...\tksheet\_tksheet_main_table.py", line 4631, in <lambda>
    lambda event: self.get_dropdown_value(canvas_window = window,
  File "...\tksheet\**_tksheet_main_table.py**", line 4656, in get_dropdown_value
    c = self.displayed_columns[cpos]
IndexError: list index out of range

Here is a small script to reproduce it, it happens when selected a dropdown value:
(or tell me if I'm doing wrong ?)

> import tkinter as tk
> from tksheet import Sheet
> root = tk.Tk()
> frame = tk.Frame(root)
> data = [
>     ["AAA", "AAA", "AAA"],
>     ["CCC", "CCC", "CCC"],
>     ["XXX", "XXX", "XXX"]
> ]
> sheet = Sheet(frame, data=data)
> sheet.pack(expand=tk.YES, fill=tk.BOTH)
> sheet.enable_bindings(
>     (
>         "single_select",  # "single_select" or "toggle_select"
>         "arrowkeys",
>         "edit_cell",
>     )
> )
> sheet.create_dropdown(1, 1, values=['AAA', 'BBB', 'CCC'], set_value="BBB")
> sheet.see(0,0)
> frame.pack(fill=tk.BOTH, expand=tk.YES)
> root.mainloop()
> 

Thank you for your help

**Comment by ragardner** [comment]
Sorry about that, it appears to be a bug, I have hopefully fixed it in version `4.9.98`

**Comment by skedus** [comment]
Thanks for your quick feedback :-)
