### ISSUE TITLE
set_all_cell_sizes_to_text and dropdown

### ISSUE THREAD

**Issue by skedus** [ragardner/tksheet#57]
Hi,
I would like to use the auto resize : set_all_heights_and_widths=True corresponding to set_all_cell_sizes_to_text()
is it possible either
- to increase the column width when a dropdown is present in the column
or 
- at least having a global option to increase column width to text_size + custom_size_option which will allow to increase globally all column with something like 20 

below a small example of the actual display the cell value is not visible when a dropdown is present.

Thanks for your help

```
import tkinter as tk
from tksheet import Sheet
root = tk.Tk()
frame = tk.Frame(root)
data = [
    ["AAA", "AAA", "AAA"],
    ["CCC", "CCC", "CCC"],
    ["XXX", "XXX", "XXX"]
]
sheet = Sheet(frame, data=data, set_all_heights_and_widths=True)
sheet.pack(expand=tk.YES, fill=tk.BOTH)
sheet.enable_bindings(
    (
        "single_select",  # "single_select" or "toggle_select"
        "arrowkeys",
        "edit_cell",
        "column_width_resize",
    )
)
sheet.create_dropdown(1, 1, values=['AAA', 'BBB', 'CCC'], set_value="BBB", destroy_on_select = False)
sheet.see(0,0)
frame.pack(fill=tk.BOTH, expand=tk.YES)
root.mainloop()

```

**Comment by ragardner** [comment]
Thanks for your feedback,

In version `4.9.99` (released just now) I have made the changes:

### Version 4.9.99
 - Fixed bugs with row copying where `list(repeat(list(repeat(` was used in code to create empty list of lists
 - Made cell resize to text (width only) take dropdown boxes into account

So resizing should show the whole cell value for you now, but one thing you have to take into account; with your existing example above you are adding the dropdown box after sheet creation which means that resizing is not taking the box into account, I have made adjustments to your example so it should work correctly with the new version:

```python
import tkinter as tk
from tksheet import Sheet
root = tk.Tk()
frame = tk.Frame(root)
data = [
    ["AAA", "AAA", "AAA"],
    ["CCC", "CCC", "CCC"],
    ["XXX", "XXX", "XXX"]
]
sheet = Sheet(frame, data=data)
sheet.pack(expand=tk.YES, fill=tk.BOTH)
sheet.enable_bindings(
    (
        "single_select",
        "arrowkeys",
        "edit_cell",
        "column_width_resize",
        "double_click_column_resize" # added double click column resize
    )
)
sheet.create_dropdown(1, 1, values=['AAA', 'BBB', 'CCC'], set_value="BBB", destroy_on_select = False)
sheet.see(0,0)
sheet.set_all_cell_sizes_to_text() # cell resizing moved here
frame.pack(fill=tk.BOTH, expand=tk.YES)
root.mainloop()
```

Let me know if it works for you

**Comment by skedus** [comment]
Thank you, this is working for windows and linux (v5.0.0)
Thanks for your adjustments  ;-)
