### ISSUE TITLE
[Question] Multiple rows insert results in clone rows?

### ISSUE THREAD

**Issue by crb777** [ragardner/tksheet#58]
First of all, congratulations for this awesome development. I have been using it in an application and it works very nice. I have an issue and I would like to know if you have the same one or I did something wrong.
I have a, let's say, 5x5 table. The user selects the middle row and drags down to select rows 3, 4 and 5. If he makes right click insert rows, now he can see rows 1 and 2. Then 3 empty rows. Then rows 6, 7 and 8. But the empty rows seem to be clones of each other! That is, if he writes A in the first cell of Row 3, the same A appears in rows 4 and 5. If he writes B in row 4, the same appears in rows 3 and 5. Could you, please, check if this is a bug or it just happens to me? I would like to be sure that it is not my mistake.
Thank you very much and congratulations once again.
Best regards

**Comment by ragardner** [comment]
Sorry about that it was indeed a bug, it should be fixed in `4.9.99`

**Comment by crb777** [comment]
Thank you very much, that sounds great! I will stay tuned in.
Best regards.
