### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by namnguyen7697** [ragardner/tksheet#6]
Hi, Thanks for your contribute... it's very nice. It helped me a lot.
I have a question, i want to set position, width and height for showtable, i see it in __init__ of sheet, but it doesn't seem to work.. Can you answer for me?
Thank you very much!

**Comment by ragardner** [comment]
Thanks,

You are correct about height and width not working, I will be updating the library soon with the fix, if you need an immediate fix you can put inside the `__init__` function in `_tksheet.py`

`self.grid_propagate(0)`

**Comment by ragardner** [comment]
@namnguyen7697 I have just added the height and width changes to the latest version on pypi
