### ISSUE TITLE
how to remove empty area below table tksheet

### ISSUE THREAD

**Issue by skedus** [ragardner/tksheet#60]
Hi, 
I try to use 2 tksheet tables in the same frame, I tested various things to manage height, but I still have an empty area below each table, is there a way to manage this empty area ? it is may be due to an option I didn't find ?

Thank you

Here below a small example to reproduce it:

![tksheet01](https://user-images.githubusercontent.com/63906254/108218158-aa0aba80-7134-11eb-8216-134b52271e4f.png)

```
import tkinter as tk
from tksheet import Sheet

root = tk.Tk()
frame=tk.Frame(root) 

data1 = [
    ['value11','value12','value13'],
    ['value21','value22','value23'],
]
data2 = [
    ['value11','value12','value13','value14'],
    ['value21','value22','value23','value24'],
    ['value31','value32','value33','value34'],
]

title1 = tk.Label(frame, text="Table #1")
title1.pack(side=tk.TOP, fill=tk.X)
sheet1 = Sheet(frame, data=data1)
sheet1.pack(expand=tk.YES, fill=tk.BOTH)

title2 = tk.Label(frame, text="Table #2")
title2.pack(side=tk.TOP, fill=tk.X)
sheet2 = Sheet(frame, data=data2)
sheet2.pack(expand=tk.YES, fill=tk.BOTH)

frame.pack(fill=tk.BOTH, expand=tk.YES)

root.mainloop()
```

**Comment by ragardner** [comment]
Unfortunately I think they are that size because that's the default size of a canvas without a height and width input, in order to fix this I would use the `height` option and set a height in pixels

I updated the library just now with this change:
 - Add default height and width if a height is used without a width or vice versa

It means that if you set a height but not a width it will set the width to 350, it has to because otherwise the whole table becomes hidden

```python
sheet1 = Sheet(frame,
               data = data1,
               height = 150)
               #width = 400)
```

You can also use the options `empty_vertical = <extra vertical white space inside table in pixels>` and `empty_horizontal` but these will only impact space inside the table not the actual table dimensions

![image](https://user-images.githubusercontent.com/26602401/108241210-800cc480-7143-11eb-98e3-e6c421e1180a.png)

**Comment by skedus** [comment]
I do not think about canvas itself, good catch thank you ;-)
Sorry for all my request those days but I will use tksheet in my application in various situation (and on linux and windows platform)
I really appreciate your support thanks

Before closing this ticket a small question do you think it is possible to activate scrollbar only if table is not fully visible, I have seen some functions cell_is_visible,  cell_is_completely_visible, ... may be based on those functions ? 
it is only a question (nice to have) but not necessary ;-)

**Comment by skedus** [comment]
Really great :-) it is ok
Thank you

Here is the result on windows / Linux
handle the empty area and automatic scrollbar

![tksheet_02](https://user-images.githubusercontent.com/63906254/108393124-a7cb5d80-7213-11eb-8243-731b93b4bb15.png)
![tksheet_03](https://user-images.githubusercontent.com/63906254/108393127-a8fc8a80-7213-11eb-913b-9191bbd2233b.png)

code example:

```
import tkinter as tk
from tksheet import Sheet

root = tk.Tk()
frame=tk.Frame(root) 

data1 = [
    ['value11','value12','value13'],
    ['value21','value22','value23'],
]
data2 = [
    ['value11','value12','value13','value14'],
    ['value21','value22','value23','value24'],
    ['value31','value32','value33','value34'],
]

title1 = tk.Label(frame, text="Table #1")
title1.pack(side=tk.TOP, fill=tk.X)
sheet1 = Sheet(frame, data=data1, height = 100, empty_horizontal = 10, empty_vertical = 10)
sheet1.pack(expand=tk.YES, fill=tk.BOTH)

title2 = tk.Label(frame, text="Table #2")
title2.pack(side=tk.TOP, fill=tk.X)
sheet2 = Sheet(frame, data=data2, height = 100, empty_horizontal = 10, empty_vertical = 10)
sheet2.pack(expand=tk.YES, fill=tk.BOTH)

frame.pack(fill=tk.BOTH, expand=tk.YES)

root.mainloop()


```
