### ISSUE TITLE
Undo extra binding need more inputs

### ISSUE THREAD

**Issue by skedus** [ragardner/tksheet#62]
Hi,
I need to use the extra binding 'end_undo' , 'end_ctrl_z'
but I have not enough inputs, only the type of undo such 'edit_cell'

- today event contain :  **("end_ctrl_z", undo_storage[0])**

Is it possible to get all the undo storage element ?  **("end_ctrl_z", undo_storage)**

I modified _tksheet_main_table.py as follow and it works fine for me:

https://github.com/ragardner/tksheet/blob/53d244b0222d92540c46de9d1eb78ce928646611/tksheet/_tksheet_main_table.py#L760

`self.extra_begin_ctrl_z_func(("begin_ctrl_z", undo_storage))`

and:

https://github.com/ragardner/tksheet/blob/53d244b0222d92540c46de9d1eb78ce928646611/tksheet/_tksheet_main_table.py#L1051

`self.extra_end_ctrl_z_func(("end_ctrl_z", undo_storage))`

It is then possible to use the full undo content, outside tksheet for custom external structures (link to tksheet, especially read/write functionality)

Is it possible to include this fix in the next release ?
Thank you

**Comment by ragardner** [comment]
I am reluctant to modify the two variables as they are because others may have to rewrite their code, but I can extend the event and add the full undo storage on the end, it would look like this

‘ self.extra_end_ctrl_z_func(("end_ctrl_z", undo_storage[0], undo_storage))’

Is this okay?

**Comment by skedus** [comment]
yes I understand, it is ok for me ;-)

**Comment by ragardner** [comment]
New release notes:

### Version 5.0.13
 - Add extra variable to undo event
 - Edit cell no longer creates undo if cell is left unchanged

**Comment by skedus** [comment]
Thank you
