### ISSUE TITLE
Row/Column Span

### ISSUE THREAD

**Issue by CapGia** [ragardner/tksheet#63]
Is it possible to define rows or columns span and  if not is there a workaround to obtain that effect?

**Comment by ragardner** [comment]
Sorry I don't know exactly what you mean by column span, do you mean the widths of all columns?

**Comment by CapGia** [comment]
I would like to merge Teo or more cells together, something like in excel

Il gio 4 mar 2021, 18:02 ragardner <notifications@github.com> ha scritto:

**Comment by ragardner** [comment]
Oh I see sorry, no currently it is not possible to do so

There isn't really a workaround, I think it would require a significant amount of new code to be written

**Comment by CapGia** [comment]
Great, thanks!

Il sab 6 mar 2021, 17:05 ragardner <notifications@github.com> ha scritto:
