### ISSUE TITLE
Do you have cell merging

### ISSUE THREAD

**Issue by ddord** [ragardner/tksheet#64]
Hello,

![image](https://user-images.githubusercontent.com/55485814/111758795-3c42e180-88e0-11eb-9886-00f66d7f145e.png)

I want to implement it the same as the screenshot above.
I'd like to ask if it's possible.

**Comment by ragardner** [comment]
Sorry it is not possible

**Comment by ddord** [comment]
> Hello,
> 
> ![image](https://user-images.githubusercontent.com/55485814/111758795-3c42e180-88e0-11eb-9886-00f66d7f145e.png)
> 
> I want to implement it the same as the screenshot above.
> I'd like to ask if it's possible.
