### ISSUE TITLE
Data from an iterable of tuples

### ISSUE THREAD

**Issue by alaindebecker** [ragardner/tksheet#65]
I am using tksheet to display results of petl.

It gives very nice results. However petl tables are iterables of tuples, which must be converted into list of lists to feed `set_sheet_data`. It is not difficult, but it is time consuming to display large tables, even when extracting small packs of them.

I am wondering what would imply changing the type of the MainTable.data_reference into an iterable of  Sequences.

**Comment by ragardner** [comment]
I can make it easier to automatically work with a tuple of tuples as long as you don't mind not being able to use such inbuilt functionality as editing cells, inserting columns/rows and dragging and dropping columns/rows as these will cause errors without a list of lists internally

**Comment by alaindebecker** [comment]
I am using `tksheet `as display only. I don't think editing the table on the display will ever make any sense in this use case.

A list of tuples will be enough to improve performance.

Thanks for the quick answer and congratulations for all the previous work.

**Comment by ragardner** [comment]
You can update to `5.0.2` and it should let you use a list of tuples with set_sheet_data() or alternatively you can use the argument `verify = False` with set_sheet_data()

### Version 5.0.2
 - `set_sheet_data()` no longer verifies by default that data is list of lists (inbuilt functionality such as cell editing still requires list of lists though)
 - Initialization argument `data` allows tuple or list

Let me know if you have any problems

**Comment by alaindebecker** [comment]
Works like a charm.
Save of few lines of code in each implementation, latency time at each run and a poltergeist to maintain.
