### ISSUE TITLE
Add new columns/rows automatically when pasting a larger matrix

### ISSUE THREAD

**Issue by fhh2626** [ragardner/tksheet#66]
Hi @ragardner,

First of all, thanks for your excellent work! 
Currently, one can copy a matrix from, say excel, to tksheet. However, if the size of tksheet is 2*3 and one want to paste a matrix with a size of 5*6, the exceeding data will be simply abandon. The expect behavior should be expanding the sheet automatically. Is there any way to achieve this?

Thanks!
fhh2626

**Comment by ragardner** [comment]
This functionality would take me some time to add as there are some complexities, especially with Undo and I have pretty much finished working on this repository

If you wanted to try to add it yourself you could try something like (in file `_tksheet_main_table.py`) changing the lines
```python
if x1 + numcols > len(self.col_positions) - 1:
    numcols = len(self.col_positions) - 1 - x1
if y1 + numrows > len(self.row_positions) - 1:
    numrows = len(self.row_positions) - 1 - y1
```

to something like

```python
if x1 + numcols > len(self.col_positions) - 1:
    self.insert_col_positions(widths = x1 + numcols - len(self.col_positions) - 1)
if y1 + numrows > len(self.row_positions) - 1:
    self.insert_row_positions(heights = x1 + numrows - len(self.row_positions) - 1)
```

this might work, I haven't tried it out sorry

and of course Undo won't remove the extra columns

**Comment by fhh2626** [comment]
Thanks for your explanation! I will do it.
