### ISSUE TITLE
improvement for extra_begin_* binding

### ISSUE THREAD

**Issue by skedus** [ragardner/tksheet#67]
Hi  ragardner,
I known that you do not have a lot of time now on tksheet, and thank you for the documention you added - great ;-)

I have a suggestion:  for example I need to use the extra_begin_del_rows_rc_func binding

https://github.com/ragardner/tksheet/blob/8415041772c71faa623d4cf4c43ddd24baf4bce8/tksheet/_tksheet_main_table.py#L3059

In this case I use it to check if all is Ok (in my data structure) to delete the row, but if not I cannot warn tksheet to stop the process, so I added a small patch like this:

```
if self.extra_begin_del_rows_rc_func is not None:
                # add exception handling
                try:
                    self.extra_begin_del_rows_rc_func(("begin_delete_rows", seld_rows))
                except:
                    # if exception is raised stop tksheet process
                    return
```
If extra_begin_del_rows_rc_func raised any exception tksheet del_rows_rc() process is stopped
This could be done for all extra_begin_* in fact

Or may be you have a better way to do it ?
It is not blocking for me as I'm using this patch but that may help some other ?
Thanks

**Comment by ragardner** [comment]
Hey skedus,

Thanks for the suggestion, I think it is a good idea and pretty easy to add, I'm thinking an exception is probably the best way as you suggest because a return value might not be appropriate to check for `None` or `False`

**Comment by ragardner** [comment]
Should work fine in `5.0.22`
