### ISSUE TITLE
Issue with ctrl-a selecting all cells

### ISSUE THREAD

**Issue by adamddowney** [ragardner/tksheet#68]
- typing "a" to edit a cell with the character "a" instead selects all cells and puts the focus on cell(0,0).  It is not looking for the "ctrl-a" to select all cells.  Instead, you have to put the focus on a cell, then press "enter" to edit the cell, then you can type the character "a"

- unable to disable the "select_all" option

**Comment by ragardner** [comment]
This is not occurring for me on windows 10 with the latest version of tksheet

Enabling `"drag_select"` is the individual binding that enables selecting all, the logic being that if you can drag select cells there's nothing to stop you from selecting all cells

If you want you can post your OS, make sure you don't have any control/command modifiers enabled etc

**Comment by adamddowney** [comment]
thanks for checking into this!  To be fair, I am new to python so I appreciate your suggestions.  When I disable "drag_select", the issue does go away...but the "drag_select" is very nice to have enabled.  I don't believe I have any control/command modifiers enabled.  

Python version is 3.9.2
tksheet version is 5.0.24
I'm editing/running the program from visual studio code version 1.55.2
OS is Windows 10, 64-bit

Here are is a list of modules I've imported into my program:
from tkinter import *
from tksheet import Sheet
from PIL import Image, ImageTk, ImageDraw, ImageChops, ImageOps
from tkinter.filedialog import asksaveasfile, askopenfile
import tkinter as tk
import csv
import math
import sys, os, inspect

**Comment by ragardner** [comment]
for a quick fix try this code whenever you need to disable control A

```python
for s1 in ("Control", "Command"):
    for s2 in ("a", "A"):
        for widget in (sheet.MT, sheet.RI, sheet.CH):
            widget.unbind(f"<{s1}-{s2}>")
```

Just replace sheet with whatever your sheets name is

I will look into this further when I find the time

**Comment by adamddowney** [comment]
Thank you for the quick fix!  It worked great and supports my program needs.  Again, really appreciate the rapid responses and suggestions.
