### ISSUE TITLE
wrap text in a cell possible?

### ISSUE THREAD

**Issue by yucongo** [ragardner/tksheet#69]
'''https://github.com/ragardner/tksheet/blob/master/DOCUMENTATION.md#1-About-tksheet
    '''
    import tkinter as tk
    from tksheet import Sheet

    data = [[f"Row {r}, Column {c}\nnewline1\nnewline2" for c in range(50)] for r in range(500)]
    data = [
        ["AAA " * 50, "AAA", "AAA"],
        ["CCC", "CCC", "CCC"],
        ["XXX", "XXX", "XXX"]
    ]

    class demo(tk.Tk):
        def __init__(self):
            tk.Tk.__init__(self)
            self.grid_columnconfigure(0, weight = 1)
            self.grid_rowconfigure(0, weight = 1)
            self.frame = tk.Frame(self)
            self.frame.grid_columnconfigure(0, weight = 1)
            self.frame.grid_rowconfigure(0, weight = 1)
            self.sheet = Sheet(self.frame,
                               data=data,
                               # auto_resize_default_row_index = True,
                               )
            self.sheet.enable_bindings()
            self.frame.grid(row = 0, column = 0, sticky = "nswe")
            self.sheet.grid(row = 0, column = 0, sticky = "nswe")

    app = demo()
    app.mainloop()

For example, when cell 1A is clicked, those "AAA AAA ..." will wrap to column width. Is this possible? When yes, how? Thanks a lot.

**Comment by ragardner** [comment]
Unfortunately cell text wrapping like you would find in excel (where text that doesn't fit horizontally is put on newlines) is not possible, sorry

**Comment by yucongo** [comment]
Thanks.
