### ISSUE TITLE
Enabling `drag_select` -binding causes CTRL-shortcuts to function incorrectly

### ISSUE THREAD

**Issue by Inspecti** [ragardner/tksheet#70]
Hi!

This issue is probably related to  #68  . When enabling binding for `drag_select`, the keyboard shortcuts that would normally require CTRL to be pressed down, work now with only pressing the corresponding letter. This behavior is seen at least with:

- CTRL + A: selects all, works with just "a" when `drag_select` is enabled
- CTRL + Z: undo, works with just "z" when `drag_select` is enabled
- CTRL + C: copy, works with just "c" when `drag_select` is enabled
- CTRL + V: paste, works with just "v" when `drag_select` is enabled

I just updated tksheet to 5.0.24 but the same issue was present in 5.0.11.

**Comment by ragardner** [comment]
If you could post an example of your code where this occurs I would be grateful as I cannot reproduce it

**Comment by jayaranah** [comment]
Thanks the issue was fix in version 5.0.25
Im using Windows 10 OS
