### ISSUE TITLE
Unable to get data from select row

### ISSUE THREAD

**Issue by canonsky1992** [ragardner/tksheet#72]
Hello,
I cannot find any function that can help me get all data from select row.
Please help me!
Best regard

**Comment by ragardner** [comment]
You should be able to use `get_row_data(<row integer>)` https://github.com/ragardner/tksheet/blob/master/DOCUMENTATION.md#6-getting-table-data

If it isn't working for you let me know

**Comment by canonsky1992** [comment]
> You should be able to use `get_row_data(<row integer>)` https://github.com/ragardner/tksheet/blob/master/DOCUMENTATION.md#6-getting-table-data
> 
> If it isn't working for you let me know

Thank you! I have read it. But I want to add funtion to select row, and get data when my mouse click and select

**Comment by ragardner** [comment]
Sorry but before I write the code just to be clear, is it that you want a function which triggers upon a row being selected, and is it only if the row is selected by the left mouse button, both mouse buttons or if a row is selected by any means

and inside this function you would like get_row_data()?

**Comment by canonsky1992** [comment]
> Sorry but before I write the code just to be clear, is it that you want a function which triggers upon a row being selected, and is it only if the row is selected by the left mouse button, both mouse buttons or if a row is selected by any means
> 
> and inside this function you would like get_row_data()?

Thank you for your reply!! I have creat a popup menu to run a function when I right click on row.
sheet.popup_menu_add_command ( label='get_data_and_print' , func=e , table_menu  =  True , index_menu  =  True , header_menu  =  True ) 
However, I want to get data from this row and print it. Please tell me how to do it,

**Comment by ragardner** [comment]
The easiest quickest way to do this is to use the sheets currently selected box to determine which row the user has right clicked on:

```python
from tksheet import Sheet
import tkinter as tk


class demo(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self.grid_columnconfigure(0, weight = 1)
        self.grid_rowconfigure(0, weight = 1)
        self.frame = tk.Frame(self)
        self.frame.grid_columnconfigure(0, weight = 1)
        self.frame.grid_rowconfigure(0, weight = 1)
        self.sheet = Sheet(self.frame,
                           data = [[f"Row {r}, Column {c}\nnewline1\nnewline2" for c in range(50)] for r in range(500)])
        self.sheet.enable_bindings(("single_select",
                                    "drag_select",
                                    "select_all",
                                    "column_select",
                                    "row_select",
                                    "column_width_resize",
                                    "double_click_column_resize",
                                    "arrowkeys",
                                    "row_height_resize",
                                    "double_click_row_resize",
                                    "right_click_popup_menu",
                                    "rc_select"
                                    ))
        self.sheet.popup_menu_add_command("Print row data", self.new_right_click_button)
        self.frame.grid(row = 0, column = 0, sticky = "nswe")
        self.sheet.grid(row = 0, column = 0, sticky = "nswe")

    def new_right_click_button(self, event = None):
        last_selected = self.sheet.get_currently_selected(get_coords = False, return_nones_if_not = False)
        if len(last_selected) > 1 and last_selected[0] == "row":
            row_data = self.sheet.get_row_data(last_selected[1])
            print (row_data)


app = demo()
app.mainloop()
```

**Comment by canonsky1992** [comment]
> The easiest quickest way to do this is to use the sheets currently selected box to determine which row the user has right clicked on:
> 
> ```python
> from tksheet import Sheet
> import tkinter as tk
> 
> 
> class demo(tk.Tk):
>     def __init__(self):
>         tk.Tk.__init__(self)
>         self.grid_columnconfigure(0, weight = 1)
>         self.grid_rowconfigure(0, weight = 1)
>         self.frame = tk.Frame(self)
>         self.frame.grid_columnconfigure(0, weight = 1)
>         self.frame.grid_rowconfigure(0, weight = 1)
>         self.sheet = Sheet(self.frame,
>                            data = [[f"Row {r}, Column {c}\nnewline1\nnewline2" for c in range(50)] for r in range(500)])
>         self.sheet.enable_bindings(("single_select",
>                                     "drag_select",
>                                     "select_all",
>                                     "column_select",
>                                     "row_select",
>                                     "column_width_resize",
>                                     "double_click_column_resize",
>                                     "arrowkeys",
>                                     "row_height_resize",
>                                     "double_click_row_resize",
>                                     "right_click_popup_menu",
>                                     "rc_select"
>                                     ))
>         self.sheet.popup_menu_add_command("Print row data", self.new_right_click_button)
>         self.frame.grid(row = 0, column = 0, sticky = "nswe")
>         self.sheet.grid(row = 0, column = 0, sticky = "nswe")
> 
>     def new_right_click_button(self, event = None):
>         last_selected = self.sheet.get_currently_selected(get_coords = False, return_nones_if_not = False)
>         if len(last_selected) > 1 and last_selected[0] == "row":
>             row_data = self.sheet.get_row_data(last_selected[1])
>             print (row_data)
> 
> 
> app = demo()
> app.mainloop()
> ```

Thank you for your support always!!
