### ISSUE TITLE
Cell with button widget

### ISSUE THREAD

**Issue by santiram124** [ragardner/tksheet#73]
Hi,
Is it possible to implement cell with button widget? 
I have been working on a application that requires button on cell based on certain condition. 
However, for the time being I used following code to create button in a cell.

```
for r in range(0,i):
        cdt = sheetInfo.get_cell_data(r,8,return_copy=True)
        if str(cdt)=='CHECK_FILE':
            sheetInfo.set_cell_data(r,8,value='')
            x = sheetInfo.MT.col_positions[8]
            y = sheetInfo.MT.row_positions[r]
            w = sheetInfo.MT.col_positions[8 + 1] - (sheetInfo.MT.col_positions[8] +10)
            h = sheetInfo.MT.row_positions[r + 1] - (sheetInfo.MT.row_positions[r] +10)
            try:
                sheetInfo.MT.destroy_dropdown(r,8) #-No Option for button, used this to remove previous button
            except Exception as e1:
                print(e1)
            wid = tkObj.Button(text="check_file", command=lambda:click_cell_btn(),width=13,height=1,font=('verdana',7))
            wind = sheetInfo.MT.create_window((x,y),window=wid,anchor='nw')
            sheetInfo.MT.cell_options[(r,8)]={'dropdown':(wid,wind),'readonly':False}
```

**Comment by ragardner** [comment]
Hello,

Sorry for the late reply,
I think the easiest way to do this is indeed either replacing the dropdown code or duplicating it and replacing relevant sections of it, I won't be doing this myself sorry but it seems like you're on the right track with the above code

**Comment by santiram124** [comment]
Hi,
Thanks for positive note. I would prefer duplicating code for Button, Checkbox.
However, can you help me on sorting column.

**Comment by ragardner** [comment]
This should sort a column:

```python
col_to_sort = 0
self.sheet.set_column_data(col_to_sort,
                                            values = sorted(r[col_to_sort] for r in self.sheet.get_sheet_data()),
                                            add_rows = False,
                                            redraw = True)
```

For more information on natural sorting keys, here is good to start:
https://stackoverflow.com/a/16090640/7655687

**Comment by santiram124** [comment]
Thank you so much for this help...
