### ISSUE TITLE
Hiding columns

### ISSUE THREAD

**Issue by Beercow** [ragardner/tksheet#74]
I'm trying to make a popup menu to hide columns. It doesn't work correctly after hiding one column because the index updates. Could I get some help with this?

```python
def hide_column(self, event=None):
    show_columns = [*range(0, self.sheet.total_columns(), 1)]
    show_columns.remove(self.sheet.get_currently_selected(get_coords=True)[1])
    self.sheet.display_columns(indexes=show_columns, enable=True, refresh=True)
```

**Comment by ragardner** [comment]
Hello,

You're nearly there, but I had to update `tksheet` with a change to `display_columns()` to make this a bit easier

```python
def hide_columns_right_click(self, event = None):
    currently_displayed = self.sheet.display_columns()
    exclude = set(currently_displayed[c] for c in self.sheet.get_selected_columns())
    indexes = [c for c in currently_displayed if c not in exclude]
    self.sheet.display_columns(indexes = indexes, enable = True, refresh = True)
```

**Comment by Beercow** [comment]
This works. Thank you. One more question. Is there a way to get what columns are hidden? This is so I can choose a column to unhide. Thank you in advance.

**Comment by ragardner** [comment]
You can get a list of displayed columns and so also hidden columns using `.display_columns()` without arguments (in version 5.0.26) but you would have to write a function to unhide columns

I am not sure how which columns are hidden would be shown to the user without having to write a load of new code inside tksheet for some graphical boxes or something, perhaps you could upon right clicking on the header check if there are nearby hidden columns and if there are then add a new menu item which says e.g. "Show columns 1-3"

**Comment by Beercow** [comment]
Thank you. I think I have it from here.
