### ISSUE TITLE
No documentation for Hiding the Index and Header

### ISSUE THREAD

**Issue by rodrigovimieiro** [ragardner/tksheet#77]
Hi, thanks for the codes.

There is no documentation for **Hiding the Index and Header** in the [documentation](https://github.com/ragardner/tksheet/blob/master/DOCUMENTATION.md). It is only in the index. 

Thanks!

**Comment by ragardner** [comment]
I am sorry for the lateness of this reply,

To hide the index and header you would do, there has been a minor bugfix with this functionality in `5.0.28`

```python
hide("row_index")
hide("header")
hide("top_left")
```

**Comment by rodrigovimieiro** [comment]
Hello @ragardner ,

Thanks for the reply. I managed it with:

```
show_top_left = False,
show_row_index = False,
show_header = False,
```

inside `Sheet` creation. I will try your suggestion. 

Thanks. 

Best.
