### ISSUE TITLE
scrollbar disappears when window is resized

### ISSUE THREAD

**Issue by aquib-sh** [ragardner/tksheet#78]
Hi @ragardner 

While building an application I was faced with this issue.
The sheet horizontal and vertical scrollbar gets out of display when we resize the main window.
I read the discussion in issue #11. But wasn't able to find a solution after applying .grid_rowconfigure() and .grid_columnconfigure() to the sheet frame as mentioned.

![image](https://user-images.githubusercontent.com/44388122/130086788-563ac659-9eaf-42e9-b4f7-5407bb10f492.png)

Here is a minimal example of the UI code I am using.
```

import tkinter as tk
import tksheet
import pandas

class Application(tk.Tk):
    def __init__(self):
        super().__init__()
        self.sheet_frame = tk.Frame(width=100, height=300)
        self.sheet = tksheet.Sheet(self.sheet_frame, width=self.winfo_screenwidth(), height=self.winfo_screenheight()-50)
        
        self.sheet_frame.grid(row=1, column=1, sticky='W')
        self.sheet_frame.grid_columnconfigure(1, weight=1)
        self.sheet_frame.grid_rowconfigure(1, weight=1)

        self.sheet.enable_bindings(("all"))
        self.sheet.pack(expand=True,fill='both')

    def load_file(self, filename):
        """Loads the file into application by placing it into spreadsheet."""

        if not filename.lower().endswith(".csv"):
            self.df = pandas.read_excel(filename, engine='openpyxl')
        else:
            self.df = pandas.read_csv(filename)

        df_rows = self.df.to_numpy().tolist()  
        self.sheet.headers(self.df.columns.tolist())
        self.sheet.set_sheet_data(df_rows)


if __name__ == "__main__":
    app = Application()
    app.load_file('sample.csv')
    app.mainloop()
```

Here is a file for testing:
[sample.csv](https://github.com/ragardner/tksheet/files/7015117/sample.csv)

**Comment by ragardner** [comment]
The scrollbars have gone off the side of the window because you have set the sheet widget to the size of the screen, if you made the sheet widget smaller you would see the scrollbars I think

**Comment by aquib-sh** [comment]
Thanks for the reply @ragardner , I tried

```
self.sheet_frame = tk.Frame(width=self.winfo_screenwidth(), height=self.winfo_screenheight())
self.sheet = tksheet.Sheet(self.sheet_frame, width=800, height=700)

```
and

```
self.sheet_frame = tk.Frame(width=800, height=700)
self.sheet = tksheet.Sheet(self.sheet_frame, width=800, height=700)

```        

the only difference it made was that the window initialized smaller 
![image](https://user-images.githubusercontent.com/44388122/130211731-f8440e8a-1c7e-47d0-aff1-a09802627e4b.png)

but after trying to resize it again the scrollbar got hidden.
![image](https://user-images.githubusercontent.com/44388122/130211754-f73772d8-745b-41d2-8160-c3971de9a625.png)

**Comment by ragardner** [comment]
I think this is not an issue with tksheet, it's tkinter

it's because when you shrink the window the sheet and frame widgets are maintaining their specified sizes and not shrinking with the window

You will have to play around with the widgets, perhaps removing the specific sizes and letting them expand and contract with the window or messing about with `grid` options, and generally learning tkinter

https://www.pythontutorial.net/tkinter/tkinter-grid/
https://stackoverflow.com/questions/4399180/how-to-set-the-min-and-max-height-or-width-of-a-frame

**Comment by aquib-sh** [comment]
Tkinter scrollbars do not disappear when resized. I have checked that.

**Comment by ragardner** [comment]
Could you provide an example of what you have checked?

**Comment by aquib-sh** [comment]
I did some research on grid layout for this.

I found the solution was to put grid_columnconfigure and grid_rowconfigure on the root window instead of sheet frame or sheet.

Here is some explaination:

In mycase the root is self so
```
self.columnconfigure(0, weight=3)
self.rowconfigure(0, weight=3)
```

Here is the full solution:

```
import tkinter as tk
from tkinter import N, S, E, W
import tksheet
import pandas

class Application(tk.Tk):
    def __init__(self):
        super().__init__()
        self.sheet = tksheet.Sheet(self, width=800, height=500)
        
        self.sheet.enable_bindings(("all"))
        self.sheet.grid(row=0, column=0, sticky=N+S+E+W)
        self.sheet.grid_columnconfigure(1, weight=3)
        self.sheet.grid_rowconfigure(1, weight=3)

        self.columnconfigure(0, weight=3)
        self.rowconfigure(0, weight=3)


    def load_file(self, filename):
        """Loads the file into application by placing it into spreadsheet."""

        if not filename.lower().endswith(".csv"):
            self.df = pandas.read_excel(filename, engine='openpyxl')
        else:
            self.df = pandas.read_csv(filename)

        df_rows = self.df.to_numpy().tolist()  
        self.sheet.headers(self.df.columns.tolist())
        self.sheet.set_sheet_data(df_rows)


if __name__ == "__main__":
    app = Application()
    app.load_file('sample.csv')
    app.mainloop()


```
