### ISSUE TITLE
Intro key entering "\n" char instead of applying value to cell and jump to next one.

### ISSUE THREAD

**Issue by Godkayaki** [ragardner/tksheet#79]
As the title says, I'm having problems with this, I'm working on an application that works both on MacOS and Linux, and while MacOS works just fine, Linux cells work different.

Thanks in advance!

**Comment by ragardner** [comment]
Sorry for the delay,

What do you mean by intro key sorry? A key that opens the sheet cell editor?

**Comment by Godkayaki** [comment]
> Sorry for the delay,
> 
> What do you mean by intro key sorry? A key that opens the sheet cell editor?

I mean, like writing something on a cell and then clicking the return key, it normally moves you to the cell below the one you were editing, but instead on Linux, it adds a line break "\n".

**Comment by ragardner** [comment]
It should in theory only add a line break when Alt is held down so the binding is Alt-Return, is there some way Alt or Fn is being activated when you're on Linux?
