### ISSUE TITLE
ReadMe Clarifications ?

### ISSUE THREAD

**Issue by jvickroy** [ragardner/tksheet#8]
The _ReadMe_ **Features** section contains the following bullet:

- Copes with cell elements not being strings

Could you elaborate on this?  May  cells may contain arbitrary Python objects?

Also, how can sheet contents be saved to a file?

Thanks for sharing your software.
/jim

**Comment by ragardner** [comment]
Sorry yes basically it will try to display what it is given using f strings `f"{cell_element}"` so it should be able to display integers and floats

To save the contents to a file you'll first have to get all the data, unfortunately currently I don't have a direct function to do so, it's still a work in progress but you can use this to get at all the data:

```python
sheet_data = my_sheet.MT.data_ref
```

`.MT.data_ref` is the list of lists variable that holds the display data, it is a list of rows

After you have that you'll have to create a function yourself to write it to a file

**Comment by jvickroy** [comment]
Thanks for your quick response.

I have been experimenting a bit (after browsing the Sheet class code) and, from your reply, see that cells may contain any class that has a __str__ method.  Very nice!

Thanks also for the tip on .MT.data_ref.

The availability of bindings to all manner of events (illustrated in your test demo script) provides great flexibility.

**Comment by jvickroy** [comment]
Regarding Sheet.MT.data_ref, as an afterthought, I would like to suggest making the data available as a Sheet class instance property ... something like:

```
from typing import Any, List
class Sheet (tk.Frame):
    ...
    @property
    def data (self) -> List[List[Any]]:
        return self.MT.data_ref
```

**Comment by ragardner** [comment]
Thanks, I will definitely add such a function with the next update which probably will come within a week
