### ISSUE TITLE
Getting the cell data as it is being typed in the cell editor

### ISSUE THREAD

**Issue by AJAY-P-37** [ragardner/tksheet#85]
I need to create an auto-suggest drop-down for cells while it is being typed.
How to get them from the cell editor?

I'm using binding function of `begin_cell_edit` and trying to use the below code

```
get_text_editor_value(destroy_tup=(0, 0, 0), r=r, c=c,
                                                             set_data_ref_on_destroy=True, event=None,
                                                             destroy=False, move_down=True, redraw=False, recreate=False)
```
I don't understand what is destroy_tup, can you please explain?
Also is it possible to get the values from the cell editor while it is being typed by binding keys?
if yes can you show an example?
@ragardner @GerardoAllende @cpellet 
please help!

**Comment by ragardner** [comment]
If I understand correctly you are trying to make the cell editor spawn a dropdown beneath it where the values are changed as you type based on what you have typed?

**Comment by ragardner** [comment]
I think, unfortunately there is not an easy way to do this, if you really want it you will have to play around with binding stuff to your sheet to open a cell editor, like bind "any key" to your sheet and then with the bound function create a dropdown with `state = "normal"` I don't really know where to go from there sorry

I am sorry but I have limited free time and open source is not super high on my priority list
