### ISSUE TITLE
Dropdowns are recreating when scrolled

### ISSUE THREAD

**Issue by AJAY-P-37** [ragardner/tksheet#86]
I am creating a large number of dropdowns in my sheet. When I scroll horizontally, the dropdowns are being recreated rapidly which makes the UI look ugly.
My question is, is that how the dropdowns in the sheet behave or is there a way to avoid it? 

`self.sheet.create_dropdown(r=r, c=c + 1, values=['YES', 'NO'], set_value=data[0][1],
                                   destroy_on_select=False)`

This is how I create the dropdowns. `recreate=False` doesn't work.

**Comment by ragardner** [comment]
I might be able to do something about this, I will let you know hopefully within a few days if I manage to modify the way dropdowns are in the sheet

I will try to change them from actual ttk dropdowns when not being used to simple canvas lines and when clicked on they will change into a ttk dropdown and change back into canvas stuff when the dropdown box is closed
