### ISSUE TITLE
Trying to include tooltip for every column's headers

### ISSUE THREAD

**Issue by AJAY-P-37** [ragardner/tksheet#87]
I'm trying to create tooltips for the headers when I hover on the headers.

The code I tried is below.

In the tksheet file I added a function
  
```
def get_column_object(self):
        return self.CH
```

This is the code in my app
```
def __init__(self):
        self.ch = self.sheet.get_column_object()
        self.ch.bind('<Enter>',self.createtooltip)
        self.ch.bind('<Leave>', self.destroytooltip)

def createtooltip(self,event):
        column = self.sheet.identify_column(event, exclude_header = False, allow_end = True)
        column_widths = self.sheet.get_column_widths(canvas_positions=True)
        self.x = column_widths[column]
        col_name = self.sheet.headers()[column]
        if col_name == 'Col 1':
                text = 'Col1...'
        if col_name == 'Col2':
                text = 'Col2...'
        ToolTip(self.ch,x=x,y=30,text=text)
```

It works fine. But still, it would be better if I could get each column as separate objects. I tried self.ch.winfo_children() but I can't proceed further. Can you help me with this?

**Comment by ragardner** [comment]
I think with `5.2.0` I have done the best I can do short of making the little dropdown values window a top level or perhaps trying to get the root window and place it above the right position there

I might try to do this in the future, I'll let you know here if I do

**Comment by AJAY-P-37** [comment]
https://user-images.githubusercontent.com/65544154/139537256-8b2abc60-b05f-4e1d-8c36-739a6514dc41.mp4

I don't get what you are going to update in the future lol, but the bug is fixed. Thank you so much. If you are letting me know the update here, will be very useful. Thanks once again.
In the above video, you could see the horizontal scrollbar for dropdowns having lengthy options(more than the column's width). Is it a test case that you have to rectify? or should I make changes in my sheet's height?

**Comment by ragardner** [comment]
I think with `5.2.2` I have solved the above problem, but let me know if not

There have also been other changes in `5.2.1` and `5.2.2`, I improved the looks of the dropdown arrows and checkboxes and there's been bug fixes and code clean up related to having hidden columns and stuff
