### ISSUE TITLE
Getting error on deleting a row with dropdown

### ISSUE THREAD

**Issue by santiram124** [ragardner/tksheet#93]
Modified `test_tksheet.py` to add a dropdown to a cell. While deleting the entire row using right click menu an Exception is thrown. Please refer to below screenshots.

Modifications in `test_tksheet.py`:
![image](https://user-images.githubusercontent.com/81855621/141611181-cd81592c-4f22-4eab-9917-1e88b2345ed2.png)
![image](https://user-images.githubusercontent.com/81855621/141611205-709ecf3d-d37e-4797-beaa-16453b551cc6.png)
![image](https://user-images.githubusercontent.com/81855621/141611279-7e8cb6ce-4059-4549-a794-5fe56f045ebe.png)

*Exception details:*
![image](https://user-images.githubusercontent.com/81855621/141611295-62661760-ef4e-4bae-8791-f9d861cb0a4f.png)

Then I added ``` if 'checkbox' in self.cell_options[(r, c)]:``` to `destroy_checkbox` and ``` if 'dropdown' in self.cell_options[(r, c)]:``` to `destroy_dropdown` of `_tksheet_main_table.py`. 

```
    # c is dcol
    def destroy_dropdown(self, r, c):
        if 'dropdown' in self.cell_options[(r, c)]:
            self.delete_opened_dropdown_window(r, c)
            del self.cell_options[(r, c)]['dropdown']

    # c is dcol
    def destroy_checkbox(self, r, c):
        if 'checkbox' in self.cell_options[(r, c)]:
            del self.cell_options[(r, c)]['checkbox']
```

**Comment by ragardner** [comment]
Really sorry about that, it should be fixed in `5.2.3`
