### ISSUE TITLE
ImportError with Python 3.9.5

### ISSUE THREAD

**Issue by Mnikley** [ragardner/tksheet#95]
I just stumbled upon this repository and could not manage to import the module. Minimal reproducible example:
```
from tksheet import Sheet
```
Results in:
```
ImportError: cannot import name 'Sheet' from partially initialized module 'tksheet' (most likely due to a circular import) (C:\Users\XXXX\Desktop\testing\tksheet.py)
```
Tried this after creating a venv via `python -m venv venv` and after installing tksheet via `pip install tksheet`.

**Comment by ragardner** [comment]
I think it might be because the name of your test file is `tksheet.py`, try renaming it to something other than an imported library

**Comment by Mnikley** [comment]
Ah, of course! Thanks alot :)
