### ISSUE TITLE
Highlighting cells makes them read-only

### ISSUE THREAD

**Issue by kuddleofficial** [ragardner/tksheet#96]
Hey!
Could you help me figure out how to highlight cells properly? I want to give a cell a red background while still keeping it in normal mode. However, calling the function highlight_cells() puts the highlighted cells in a read-only mode. I have tried resetting the mode of the cell with readonly_cells(readonly=false), but that doesn't work.

**Comment by ragardner** [comment]
Thanks very much for the report,

It should work correctly now in `5.2.5` and your highlighted cells should be editable
