### ISSUE TITLE
Combobox size & icons

### ISSUE THREAD

**Issue by skedus** [ragardner/tksheet#97]
Hi I notice a not very nice look with combobox, not enough space between text and icon

Here is an example:
![tksheet_04](https://user-images.githubusercontent.com/63906254/143208256-248d71eb-88e9-4d12-b627-13ed58efdfca.png)

```
import tkinter as tk
from tksheet import Sheet

root = tk.Tk()
frame = tk.Frame(root)

data = [
    ["aaaa", "aaaa", "aaaa"],
    ["ccc", "ccc", "ccc"],
    ["dddddd", "dddddd", "dddddd"],
    ["xxx", "xxx", "xxx"]
]
sheet = Sheet(frame, 
    data=data,
    font=("DejaVu Sans", 9, "normal"),
    header_font=("DejaVu Sans", 9, "normal")
)
sheet.pack(expand=tk.YES, fill=tk.BOTH)

sheet.enable_bindings(
    (
        "single_select",  # "single_select" or "toggle_select"
        "arrowkeys",
        "edit_cell"
    )
)
r = 0
for row_val in data:
    c = 0
    for col_val in row_val:
        if c == 1:
            sheet.create_dropdown(r, c, values=['aaaa', 'bbbbb', 'ccc', 'dddddd', 'xxx', 'yyyyyyyyyy', 'zzz'], set_value=col_val)
        c += 1
    r += 1

sheet.see(0,0)
sheet.set_all_cell_sizes_to_text() # cell resizing moved here
frame.pack(fill=tk.BOTH, expand=tk.YES)

root.mainloop()
```

I fix it with **+ 5** here

https://github.com/ragardner/tksheet/blob/a2ae543bd21eaefc4ca631bad08ec554f76ee7dd/tksheet/_tksheet_main_table.py#L2856

```
                if txt:
                    itmcon(x, text = txt)
                    b = itmbbx(x)
here -->                    tw = b[2] - b[0] + self.txt_h + 3 + 5 if (rn, cn) in self.cell_options and 'dropdown' in self.cell_options[(rn, cn)] else b[2] - b[0] + 5
                    h = b[3] - b[1] + 5
                else:
                    if (rn, cn) in self.cell_options and 'dropdown' in self.cell_options[(rn, cn)]:
 here -->                       tw = self.txt_h + 3 + 5
                    else:
                        tw = min_cw
                    h = min_rh
 ```

This is not a very nice patch, but could you add this or a better patch to this ?

Moreover the combobox icon of tk is more like this:

![tksheet_05](https://user-images.githubusercontent.com/63906254/143209592-d48432ce-fdb5-4d02-8046-42bfe21b8eff.png)

Than:

![tksheet_06](https://user-images.githubusercontent.com/63906254/143210113-3aaf0710-fa04-4d8d-8468-483e5c5e9d13.png)

I tried to find in your code (to propose a solution) but I do not find exactly how you draw this icon, could you tell me how you are doing?

Thank you

**Comment by skedus** [comment]
I found the function redraw_dropdown:
https://github.com/ragardner/tksheet/blob/a2ae543bd21eaefc4ca631bad08ec554f76ee7dd/tksheet/_tksheet_main_table.py#L3641

**Comment by skedus** [comment]
With a small modification redraw_dropdown icon is working better (create a dash width 1 instead of 2 ligns)

![tksheet_07](https://user-images.githubusercontent.com/63906254/143244858-872420a6-62f7-42b3-b877-41d8ec679ca7.png)

only border use the text highlight not the usual cell border color (this is minor) and more difficult to fix because relative to redraw_highlight_get_text_fg function

I do not know if you will add such modifications, but thank you for the time you gave on combobox and checkbutton this is very useful

**Comment by ragardner** [comment]
Hello,

I agree with you, I have improved the looks a bit with `5.2.7` also I think the text will no longer overlap with the arrow, they are still arrows though,

I haven't done anything about the border yet, I will consider the best approach and hopefully update soon

**Comment by ragardner** [comment]
Ok, with `5.2.8` I have made the combobox box border the same table foreground color, regardless of highlight

I also fixed an error while using editable comboboxes and pressing modifier keys

I also improved the looks of the check boxes a bit I think

Let me know your thoughts when you have the time

**Comment by skedus** [comment]
This is now ok, thank you

![image](https://user-images.githubusercontent.com/63906254/143823456-ca061773-c9e6-4552-abb4-33de009164fe.png)

I really appreciate your quick resolution of this ;-)
