### ISSUE TITLE
an odd problem 

### ISSUE THREAD

**Issue by atila-gh** [ragardner/tksheet#98]
### hi dear

i have problem for adding a row data with button command function 
it can't insert row in any configuration !!!!
i know its impossible but i cant solve it 
!!!!! PLEASE HELP!!!!
###this project is very nice and practical 

####I write a simple code only for show my problem 

`
from tksheet import Sheet
from tkinter import *

def func():                        
    sheet.insert_row(values = [1,2,3], idx = 0)
   

win = Tk()

frame = Frame(win)        
sheet = Sheet(frame , headers = ['a','b','c'])

btn = Button(win , text = 'Press' , width = 20 , command = func )

frame.grid(row = 0, column = 0, sticky = "nswe")
sheet.grid(row = 0, column = 0, sticky = "nswe")
btn.grid(row = 2 , column = 0 )
  
win.mainloop()

`

**in top code when i pressed button noting happen but when i write the insert command out of function 
its work properly**

**Comment by ragardner** [comment]
Adding `redraw = True` to your function will fix it I think

```python
def func():
    sheet.insert_row(values = [1,2,3], idx = 0, redraw = True)
```

**Comment by atila-gh** [comment]
Very well , its work properly 

thanks
