### ISSUE TITLE
monitor the value change of cells

### ISSUE THREAD

**Issue by sunflyfairy** [ragardner/tksheet#99]
I'm interested in tksheet. I wonder if it has some functions to monitor the value change of cells.
when I finished a cell, then I press enter go to the next row. Just now, does some function can be binded to check the value that I just finished.

**Comment by sunflyfairy** [comment]
`    def all_extra_bindings(self, event):
        x = self.sheet.get_selected_cells()
        if x:
            r, c = list(x)[0]
            print(event)
            print(r)
            print(c)`

**Comment by ragardner** [comment]
If you haven't tried it already [this](https://github.com/ragardner/tksheet/blob/master/DOCUMENTATION.md#7-Bindings-and-Functionality) might be of interest to you, using the `"end_edit_cell"` argument

> Bind various table functionality to your own functions. To unbind a function either set func argument to None or leave it as default e.g. extra_bindings("begin_copy") to unbind "begin_copy".
> 
> extra_bindings(bindings, func = "None")
> bindings (str) options are:
> "begin_copy"
> "end_copy"
> "begin_cut"
> "end_cut"
> "begin_paste"
> "end_paste"
> "begin_undo"
> "end_undo"
> "begin_delete"
> "end_delete"
> "begin_edit_cell"
> "end_edit_cell"
> "begin_row_index_drag_drop"
> "end_row_index_drag_drop"
> "begin_column_header_drag_drop"
> "end_column_header_drag_drop"
> "begin_delete_rows"
> "end_delete_rows"
> "begin_delete_columns"
> "end_delete_columns"
> "begin_insert_columns"
> "end_insert_columns"
> "begin_insert_rows"
> "end_insert_rows"
> "row_height_resize"
> "column_width_resize"
> "cell_select"
> "select_all"
> "row_select"
> "column_select"
> "drag_select_cells"
> "drag_select_rows"
> "drag_select_columns"
> "shift_cell_select"
> "shift_row_select"
> "shift_column_select"
> "deselect"
> "all_select_events"
> "bind_all"
> "unbind_all"
> func argument is the function you want to send the binding event to.

If you print out the event it sends it should give you a name which explains each variable as well as it's a [namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple)

Let me know if this doesn't help

**Comment by sunflyfairy** [comment]
Thanks, the "end_edit_cell" argument is my requirement, but another issue arose, how can I get the r and c of the cell.
    I use "self.sheet.get_selected_cells()",it will return the next row.

**Comment by ragardner** [comment]
I'm not really sure about what you mean by an easier way, do you mean to make the code above more concise?

The event of end_edit_cell looks like this `EditCellEvent(row=2, column=5, key='Return', text='sfsdfsdf', eventname='end_edit_cell')` you can use `print (event)` to see it

The `text` variable is what the cell was changed to, you can use it like so:

```python
def is_float(self, v):
    try:
        float(v)
        return True
    except:
        return False

def end_edit_cell(self, event):
    if event.eventname == "end_edit_cell":
        r, c = event.row, event.column
        if event.text and is_float(event.text):
            v3 = event.text
            if float(v3) < v1 or float(v3) > v2:
                self.sheet.highlight_cells(row=r, column=c, bg='white', fg='red', redraw=False)
            else:
                self.sheet.dehighlight_cells(row=r, column=c, all_=False, redraw=True)
```
